# Importing the needed packages

In [1]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

# Data Access and Profiling:
###     Importing the Restaurant Menu and Nutrition dataset

In [2]:
df= pd.read_csv ('/Users/buzz/Downloads/Business Info Project/Menu.csv') 
df

/var/folders/sk/ykmmm_7n6dj04ryb4qcvnbpc0000gn/T/ipykernel_34742/134697359.py:1: DtypeWarning: Columns (9,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv ('/Users/buzz/Downloads/Business Info Project/Menu.csv')

,Menu_Item_ID,Year,Restaurant_Item_Name,restaurant,Restaurant_ID,Item_Name,Item_Description,Food_Category,Serving_Size,Serving_Size_text,...,Sodium_text,Potassium_text,Carbohydrates_text,Protein_text,Sugar_text,Dietary_Fiber_text,Kids_Meal,Limited_Time_Offer,Regional,Shareable
0,35005,2017,7 Eleven Mocha Iced Coffee,7 Eleven,1,Mocha Iced Coffee,"Mocha Iced Coffee, Chillers Iced Coffee, Drinks",Beverages,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1,35008,2017,7 Eleven French Vanilla Iced Coffee,7 Eleven,1,French Vanilla Iced Coffee,"French Vanilla Iced Coffee, Chillers Iced Coff...",Beverages,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
2,35027,2017,7 Eleven French Vanilla Cappuccino,7 Eleven,1,French Vanilla Cappuccino,"French Vanilla Cappuccino, Coffee, Drinks, Fla...",Beverages,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0
3,35028,2017,7 Eleven Peppermint Mocha,7 Eleven,1,Peppermint Mocha,"Peppermint Mocha, Coffee, 8 fl oz",Beverages,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
4,35029,2017,7 Eleven Pumpkin Spice Latte,7 Eleven,1,Pumpkin Spice Latte,"Pumpkin Spice Latte, Coffee, 8 fl oz",Beverages,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65214,118344,2018,"Einstein Bros Frozen Mocha, 24 fl oz",Einstein Bros,31,"Frozen Mocha, 24 fl oz","Frozen Mocha w/ 2% Milk, 24 fl oz, Classic, Be...",Beverages,24.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
65215,153014,2018,Dunkin' Donuts Sweet Black Pepper Bacon Wake U...,Dunkin' Donuts,30,Sweet Black Pepper Bacon Wake Up Wrap,"Sweet Black Pepper Bacon Wake Up Wrap, Breakfa...",Sandwiches,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
65216,174902,2018,LongHorn Steakhouse Whiskey Smash,LongHorn Steakhouse,53,Whiskey Smash,"Whiskey Smash w/ Jim Beam Bourbon, Fresh Squee...",Beverages,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
65217,131673,2018,Golden Corral Chicken Enchilada,Golden Corral,37,Chicken Enchilada,"Chicken Enchilada, Chicken & Turkey",Entrees,127.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
65218,136001,2018,"Del Taco Street Tacos, Carne Asada",Del Taco,27,"Street Tacos, Carne Asada",Street Tacos in 2 Tortillas w/ Carne Asada Ste...,Sandwiches,113.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0

###  * The number of observations and the number of variables in the dataset.

In [4]:
# Checking shape of dataframe
df.shape

(65219, 49)

###  *  The name and data type of each data column.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65219 entries, 0 to 65218
Data columns (total 49 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Menu_Item_ID            65219 non-null  int64
 1   Year                    65219 non-null  int64
 2   Restaurant_Item_Name    65219 non-null  object
 3   restaurant              65219 non-null  object
 4   Restaurant_ID           65219 non-null  int64
 5   Item_Name               65219 non-null  object
 6   Item_Description        65219 non-null  object
 7   Food_Category           65219 non-null  object
 8   Serving_Size            26899 non-null  float64
 9   Serving_Size_text       39 non-null     object
 10  Serving_Size_Unit       26927 non-null  object
 11  Serving_Size_household  15238 non-null  object
 12  Calories                55315 non-null  float64
 13  Total_Fat               54846 non-null  float64
 14  Saturated_Fat           54143 non-null  float64
 15  Trans_Fat               51503 non-null  float64
 16  Cholesterol             53219 non-null  float64
 17  Sodium                  54991 non-null  float64
 18  Potassium               1098 non-null   float64
 19  Carbohydrates           54288 non-null  float64
 20  Protein                 54233 non-null  float64
 21  Sugar                   52931 non-null  float64
 22  Dietary_Fiber           53440 non-null  float64
 23  Calories_100g           25878 non-null  float64
 24  Total_Fat_100g          25686 non-null  float64
 25  Saturated_Fat_100g      25285 non-null  float64
 26  Trans_Fat_100g          23828 non-null  float64
 27  Cholesterol_100g        25126 non-null  float64
 28  Sodium_100g             25853 non-null  float64
 29  Potassium_100g          623 non-null    float64
 30  Carbohydrates_100g      25592 non-null  float64
 31  Protein_100g            25531 non-null  float64
 32  Sugar_100g              25207 non-null  float64
 33  Dietary_Fiber_100g      25391 non-null  float64
 34  Calories_text           303 non-null    object
 35  Total_Fat_text          69 non-null     object
 36  Saturated_Fat_text      50 non-null     object
 37  Trans_Fat_text          10 non-null     object
 38  Cholesterol_text        358 non-null    object
 39  Sodium_text             93 non-null     object
 40  Potassium_text          2 non-null      object
 41  Carbohydrates_text      634 non-null    object
 42  Protein_text            467 non-null    object
 43  Sugar_text              591 non-null    object
 44  Dietary_Fiber_text      811 non-null    object
 45  Kids_Meal               65219 non-null  int64
 46  Limited_Time_Offer      65219 non-null  int64
 47  Regional                65219 non-null  int64
 48  Shareable               65219 non-null  int64
dtypes: float64(23), int64(7), object(19)
memory usage: 24.4+ MB

### Checking unique values and count in each column

In [7]:
cols = df.columns
cols

Index(['Menu_Item_ID', 'Year', 'Restaurant_Item_Name', 'restaurant',
       'Restaurant_ID', 'Item_Name', 'Item_Description', 'Food_Category',
       'Serving_Size', 'Serving_Size_text', 'Serving_Size_Unit',
       'Serving_Size_household', 'Calories', 'Total_Fat', 'Saturated_Fat',
       'Trans_Fat', 'Cholesterol', 'Sodium', 'Potassium', 'Carbohydrates',
       'Protein', 'Sugar', 'Dietary_Fiber', 'Calories_100g', 'Total_Fat_100g',
       'Saturated_Fat_100g', 'Trans_Fat_100g', 'Cholesterol_100g',
       'Sodium_100g', 'Potassium_100g', 'Carbohydrates_100g', 'Protein_100g',
       'Sugar_100g', 'Dietary_Fiber_100g', 'Calories_text', 'Total_Fat_text',
       'Saturated_Fat_text', 'Trans_Fat_text', 'Cholesterol_text',
       'Sodium_text', 'Potassium_text', 'Carbohydrates_text', 'Protein_text',
       'Sugar_text', 'Dietary_Fiber_text', 'Kids_Meal', 'Limited_Time_Offer',
       'Regional', 'Shareable'],
      dtype='object')

In [9]:

# for each column
for col in cols:
    print(col)

    # get a list of unique values
    unique = df[col].unique()
    print(unique, '\n*************************************\n\n')

Menu_Item_ID
[ 35005  35008  35027 ... 172124 177768 174902]
*************************************


Year
[2017 2018]
*************************************


Restaurant_Item_Name
['7 Eleven Mocha Iced Coffee' '7 Eleven French Vanilla Iced Coffee'
 '7 Eleven French Vanilla Cappuccino' ...
 'Wawa Butter, Regular, for Junior Hot Hoagies'
 "Dunkin' Donuts Sweet Black Pepper Bacon Wake Up Wrap"
 'LongHorn Steakhouse Whiskey Smash']
*************************************


restaurant
['7 Eleven' "Applebee's" 'Chuck E. Cheese' "Arby's" 'Red Robin'
 "BJ's Restaurant & Brewhouse" 'Bonefish Grill' "Auntie Anne's"
 "Captain D's" 'Wawa' 'Sbarro' 'Bojangles' "O'Charley's" 'Baskin Robbins'
 'Bob Evans' 'Dominos' "Jimmy John's" "Friendly's" 'Boston Market'
 'Burger King' 'California Pizza Kitchen' "Carl's Jr."
 "Carrabba's Italian Grill" "Casey's General Store"
 "Checker's Drive-In/Rallys" 'Chick-Fil-A' "Chili's" 'Chipotle'
 "Church's Chicken" 'Olive Garden' "Hardee's" "Ci Ci's Pizza" "Culver's"
 'Dairy Queen' 'Einstein Bros' 'Del Taco' "Marco's Pizza" "Zaxby's"
 "Moe's Southwest Grill" "Denny's" "Dunkin' Donuts" 'Hooters'
 'Firehouse Subs' "Frisch's Big Boy" 'Outback Steakhouse' 'IHOP'
 "Jason's Deli" "Famous Dave's" "PF Chang's" 'El Pollo Loco' 'Five Guys'
 'Panda Express' "Joe's Crab Shack" 'Golden Corral' 'In-N-Out Burger'
 'Jack in the Box' 'KFC' 'Jamba Juice' 'Krispy Kreme' "McDonald's"
 "Jersey Mike's Subs" 'Yard House' 'Krystal' "Long John Silver's"
 "Steak 'N Shake" 'Little Caesars' 'LongHorn Steakhouse'
 "McAlister's Deli" 'Sheetz' 'Noodles & Company' 'On the Border'
 "Papa John's" 'Panera Bread' 'Popeyes' 'Quiznos' "Papa Murphy's"
 'Tim Hortons' 'Pizza Hut' 'Perkins' "TGI Friday's" 'Qdoba' 'Red Lobster'
 "Romano's Macaroni Grill" 'Round Table Pizza' 'Ruby Tuesday' 'Sonic'
 'Taco Bell' 'Starbucks' 'The Capital Grille' "Wendy's" 'Subway'
 'Whataburger' 'White Castle' 'Wingstop' "Dickey's Barbeque Pit"
 'Potbelly Sandwich Shop']
*************************************


Restaurant_ID
[ 1  2 22  3 73  7 10  4 14 87 77  9 58  5  8 29 46 36 11 12 13 15 16 17
 18 19 20 21 23 59 38 24 25 26 31 27 94 93 56 28 30 39 34  6 61 40 44 33
 67 32 35 62 47 37 41 42 48 43 49 55 45 92 50 52 81 51 53 54 78 57 60 64
 63 69 71 65 86 68 66 84 70 72 74 75 76 79 83 80 85 88 82 89 90 91]
*************************************


Item_Name
['Mocha Iced Coffee' 'French Vanilla Iced Coffee'
 'French Vanilla Cappuccino' ... 'Butter, Regular, for Junior Hot Hoagies'
 'Sweet Black Pepper Bacon Wake Up Wrap' 'Whiskey Smash']
*************************************


Item_Description
['Mocha Iced Coffee, Chillers Iced Coffee, Drinks'
 'French Vanilla Iced Coffee, Chillers Iced Coffee, Drinks'
 'French Vanilla Cappuccino, Coffee, Drinks, Flavors Vary by Region & Seasonally, 8 fl oz'
 ...
 'Whiskey Smash w/ Jim Beam Bourbon, Fresh Squeezed Lemon, Orange Juice, Dash of Lemon Bitters & Italian Black Amarena Cherry, Signature Bourbon Cocktails, Beverages, Steakhouse Drinks, Where Available'
 'Chicken Enchilada, Chicken & Turkey'
 'Street Tacos in 2 Tortillas w/ Carne Asada Steak, Chili Salsa, Onions, Cilantro & Avocado, Tacos & Tostadas']
*************************************


Food_Category
['Beverages' 'Entrees' 'Pizza' 'Sandwiches' 'Burgers' 'Salads'
 'Appetizers & Sides' 'Baked Goods' 'Desserts' 'Soup'
 'Toppings & Ingredients' 'Fried Potatoes']
*************************************


Serving_Size
[  nan   8.  227.  ... 419.9 700.  547. ]
*************************************


Serving_Size_text
[nan "'5-6" '18-25' "'12-20" '16-24' '10.98-11.00' '14.00-56.00'
 '7.00-28.00' '14.00-54.00' '138-139' '12.00-20.00' '620.00-1350.00' 'oz'
 '5.00-6.00' '16.00-24.00' '300.00-680.00']
*************************************


Serving_Size_Unit
[nan 'fl oz' 'g' 'oz' 'ml']
*************************************


Serving_Size_household
[nan '1 Cup' '6 Stix' '12 Pretzels' '8 Pretzels' '1 Packet' '1 Order'
 '5 Stix' '10 Pretzels' 'Small' '2 Slices' 'Regular' '1 Scoop' '2 Scoops'
 'Full Rack' 'Half Rack' '1 Slice' '4 Slices' '6 Slices' '8 Slices'
 '1 Slice, 10 Servings per Pizza' '1 Slice, 4 Servings per Pizza'
 '1 Slice, 6 Servings per Pizza' '1 Slice, 8 Servings per Pizza'
 'Half Sandwich' '1 Serving' 'Bowl' '1 Slice, 12 Servings per Pizza'
 '2 Pieces' '1 Knot' '1 Slice, 4 Servings Per Pizza'
 '1 Slice, 12 Servings Per Pizza' '1 Side' '1 Cone' '1/2 Cup' '1/8 Cake'
 '1/16 Cake' '1 Sandwich' '1/9 Pie' '1 Cookie' '2-4 Servings'
 '16 Servings' '1 Breast' '2 Each' '1 Each' 'Cup' '1 Side Dish' 'Crock'
 'Full' 'Full Sandwich' 'Half' '1 Entree' '1 Crepe' 'Entree' 'Side'
 '1 Bowl & 2 Biscuits' '2 Eggs' '1 Appetizer' '1 Bowl' '1 Ramekin'
 '1 Sundae' '1 Giant Cookie' 'Large' '1/4 Cup' '4 Each' '12 Pieces'
 '1 Leg' '1 Thigh' '1 Wing' '3 Each' '2 Crepes' '1 Brownie' '1 Whole Pie'
 '4 Pancakes' '1 Whole' '2 Breasts' '3 Slices' '2 Tbsp' '8 Pieces'
 '1/8 Cup' '1 Side & 2 Slices' '1 Full Sandwich' '5 Slices' '2 Links'
 '1 Link' '1 Loaf' '1 Slice & 1 Scoop' '1 Egg' '3 Eggs' '3 Egg Whites'
 '1 Omelet' '2 Piece Entree' 'Regular Size' 'Full Size' '1/3 Cup'
 '1 Biscuit, 1/2 Dish' '1 Biscuit, 1/6 Dish' '1 Bottle' '1 Carton'
 '6 Jumbo Shrimp' '2 Tails' '1 Portion' '1 Dessert' '1 Salad'
 '3-6 Servings' '1 Roll' 'Plate' 'Full Salad' '1/2 Salad' '2 Rolls'
 '3 Rolls' '1 Pizza' 'Bottle' '1/2 Sandwich' '7" Pizza' '1 Potato' 'Split'
 '1 Filet' '1 Piece' '1 Shrimp' '1 Tender' '1 Skewer' '1 Cake' '10 Pieces'
 '24 Pieces' '1 Burger' '4 Pieces' '6 Pieces' '9 Pieces' '1 Kids Bag'
 '1 Small Carton' '1 Medium Carton' '1 Large Carton' '1 Hamburger'
 '1 Burrito' '3 Pieces' '5 Pieces' '5 Pieces, 2 Servings per Dish'
 '5 Pieces, 3 Servings per Dish' '5 Pieces, 4 Servings per Dish' '1 Taco'
 'Medium' 'Kids' '1 Portion Cup' 'Whole Sandwich' '1 Chop' '2 Chops'
 '2 Mini Cannoli' '4 Servings' '10 Wings' '20 Wings' '1/4 lb'
 '1 Warmer Slice' '6"' '1 Large Slice'
 '1 Large Slice, 12 Servings per Pizza' '20 Pieces' '1/2 lb' '5 pieces'
 '12 Count' '4 Count' '3 Count' '8 Count' '2 Count' '1 Count' '6 Count'
 '4 Nuggets' '3 Tacos' '3 Enchiladas' '3 Tortillas' '1 Stick' '8 Servings'
 '1 Serving; 2 Servings per Dish' '1 Serving; 4 Servings per Dish'
 '1 Serving; 6 Servings per Dish' '1 Serving; 8 Servings per Dish'
 '10 Slices' '12 Slices' '16 Slices' '1 Square' '5 Wings, 1/2 Dish'
 '5 Wings, 1/4 Dish' '5 Wings' '1 Container' '4 Tenders' '2 Scoop'
 '3 Scoop' 'Mini Scoop' '3 Scoops' 'Over 1/3 lb' '1 Wrap' '1 Hot Dog'
 '2 Strips' '1 Banana' '3 Strips' 'Mini' '1 Corn Dog' '1 Biscuit'
 '5 Sticks' '8 Sticks' '1 Muffin' '1 Tsp' '3 Pancakes' '3 Rings'
 '1 Sausage' '1 Tbsp' '4 Sticks' '2 Pancakes' '16 Piece' '32 Piece'
 '1/4 of Pizza' '1 Bagel' '1/8 of Pizza' '1/8 of  Pizza' '1/2 Bread Bowl'
 '1 Dish' '1 Bismark' '1/6 of Pizza' '8 Piece' '14 Piece' '40 Piece'
 '8 Wings' '14 Wings' '40 Wings' '1/3 of Pizza' 'X Large' '12 Piece Bites'
 '2 Liter' '1 Donut' '1 Danish' '1/6 of Pizza; 1/8 of Pizza' '12 Piece'
 '1 Croissant' '1 Fritter' '1 Coffee Roll' '1 Eclair' '1 Munchkin'
 '1 Bagel Twist' '1 Unit' '1 Shot' '1 Flatbread' '1 Long John'
 '1 Croissant Donut' '1 Kolache' '1 Cob' '12 Wings' '1/2 Bagel' 'Packet'
 '2 Tortillas' '2 Churros' '3-4 Servings' '5-6 Servings' '2 Legs'
 '1/2 Order' '2 Tostadas' '2 Tacos' '60 Pieces' '1/4 Order' '1/2 Slab'
 'Full Slab' '1 Spear' '1 Sub' '2 Slice' '4 Slice' '2 Small'
 '1/4 of Fruit' '3 Tbsp' '1 Bar' '1 Patty' '2 Fillets' '5 Fillets'
 '3 Fillets' '1 Dip' '1 Pancake' '1 Strip' '2 Biscuits' '2 Sticks'
 '1 Fillet' '6 Each' '10 Each' '7 Each' '15 Each' '8 Each' '20 Each'
 '1 Package' '5 Each' '2 Each w/ Sauce' 'About 2 Slices' '5 Piece'
 '3 Piece' '10 Piece' '20 Piece' '50 Piece' '24 Piece' '6 Oysters' '1 lb'
 '.5 lb' '15 Pieces' '50 Wings' '6 Wings' '15 Piece' '6 Piece' '4 Strips'
 '2 Patties' '1 Tortilla' '4 Links' '5 Pancakes' 'Per Cup' '7 Pieces'
 '8 Pancakes' '1 Meal' '55 cc scoop' '1 Muffaletta' '1/2 Muffaletta'
 '1/4 Muffaletta' '1 order' '1 Bag' '1 Breakfast Pastry'
 '1 Bagel w/ Plain Cream Cheese' '1 Pasta' '1 Ice Cream' '1/2 Wrap'
 '1/4 Bar' '1 Sugar Cookie' '8 Nuggets' '8" Sub' '10 Shrimp' 'Individual'
 '1 Turnover' '1 Pouch' '1 Go Cup' '1/2 Gallon' '3 Tenders' '16 Pieces'
 '12 Tenders' '6 Tenders' '4 Holes' '2 Doughnuts' '3 Doughnuts' '5 Holes'
 '12 Burgers' 'Whole Pizza' '1 Snack Box' '1 oz' '1 Dipping Cup' '0.5 oz'
 '1 Cobbette' '1 Whole Pepper' '2 Pups' '2 Servings' 'Longneck Bottle'
 'Glass' 'LongPour' 'Full Portion' '2 Skewers' 'Lighter Portion' 'Mug'
 '1/3 lb' '1/3 Rack' '1/2 Rack' 'Larger Portion'
 '1 Dipper, 1/8 Chicken Dippers' '1/16 Serving' '1 14" Pizza'
 '1 12" Pizza' '1 10" Pizza' '1 16" Pizza' '1 Slice; 1/8 Pizza'
 '1 Slice; 1/6 Pizza' '1 Slice; 1/12 Pizza' '1 Slice; 1/16 Pizza'
 '1/4 Large Salad' '1/2 Small Salad' '1/2 12" Sub' '1 6" Sub'
 '1 Slice, 1/8 Pizza' '1/4 Large Salad, 1/2 Small Salad' '1/2 Large Salad'
 '1 Slice; 1/6 Pizza, 1 Slice; 1/12 Pizza'
 '1 Slice; 1/8 Pizza, 1 Slice; 1/12 Pizza' '1 Spud' '1 Plating'
 '1 Plating; Serves 2-4' '1 Dessert; 1 Serving' '1 Cookie; 1 Dessert'
 '1 Sandwich; Serves 2-4' '9 in' '1 Pack' '2 Tsbp' 'Gallon' '4 in' '6 in'
 '4 In' '1 Serving; 1 Dessert' 'Half Gallon' '1/2 Bun' '4 McNuggets'
 '6 McNuggets' '10 McNuggets' '20 McNuggets' '40 McNuggets' '12 in'
 '10 in' '8 in' '1 Full Rack' 'Half Salad' 'Whole Pie' '1 Breadstick'
 '1 Liter' '1/2 Liter' '1/4 Dish' '1/2 Dish' '2 Egg Rolls' '6 Dumplings'
 '2 Spring Rolls' '4 Spring Rolls' '4 Dumplings' '1.5 Tbsp' '1 Baguette'
 '1 Scone' '1 Muffie' '1 Souffle' '1 Miche' '1 XL Loaf' '1 Pastry'
 '1 Mini Scone' '1 Panini' '1 Tube' '2 Cups' '1 1/3 Cups' '1 Parfait'
 '1 Apple' '1 tube' '1 Tub' '9 Scones' '1 Bread Bowl' 'Half Panini'
 '2 Flatbreads' '1 Slice; 1/6 Order' '1 Slice; 1/8 Order'
 '1 Slice; 1/10 Order' '2 Sticks; 1/5 Order' '2 Wings'
 '1 Slice; 1/4 Order' '1 Pepper' '1 Slice, 1/4 Pizza'
 '1 Stick, 1/14 Order' '16 Wings' '24 Wings' '32 Wings' '15 Poppers'
 '30 Pieces' '45 Pieces' '2 Liter; 1 Bottle' '1 Square; 1/9 Order'
 '2 Sticks; 1/4 Order' '1 Stick; 1/6 Order' '1 Stick; 1/14 Order'
 'Whole Tray' '1 Slice, 1/8 Order' '1 Slice; 1/4 Pizza'
 '1 Slice, 1/6 Pizza' '1 Slice; 1/12th pizza' '1/8th Cup'
 '1 Slice; 1/8th Pizza' '1/2 Packet' '1/8 Tub' '2 Jumbo Biscuits'
 '1 Mammoth Muffin' '1 Sticky Bun' '1 Slice, 1/6 of Pie'
 '3 Potato Pancakes' '4 Shrimp' '2 Pork Chops' '2 Potato Pancakes'
 '1 Triple Decker Sandwich' 'Whole Pan' '1 Cheese Stick'
 '1 Chicken Tender' '1 Garlic Knot' '1 Cheesestick' '1 Garlic Cheesestick'
 '1/6 Brownie' '1/9 Brownie' '1/6 Slice' '1/8 Slice' '2 Ladles' '1 Ladle'
 'Each' '1/2 Portion' '1.25 lb' '12 Shrimp' '5 Shrimp' '6 Shrimp'
 'Extra Large' '1 1/2 lbs' '1 Whole Lobster' '12 Oysters' '1/3 Salad'
 '1 Slice; 1/2 Flatbread' '1 Slice; 1/6 Flatbread' '1 Stromboli' '4 Cut'
 '1 Pretzel' '1 Bucket' '1 BLT Dog' '5 Strips' '1 Gallon' '1 Glass'
 'Kids Size' 'Lunch Portion' '1 Shooter' '3 Silver Dollar Pancakes' 'Can'
 '2 Mini Buns' '3 Shooters' '3 Mini Steakburgers' '2 Tsp' '3 Chips'
 '3 Wheels' '2 Racks' '36 Wings' '1 Gordita' '1 Chalupa' '1 Quesadilla'
 '1 Crunchwrap' '1 Empanada' '1 Roll Up' '1 Coffee' '4 Pack' '2 Pack'
 '1 Quesarito' '1 Mini Quesadilla' '1 Tostada' 'XL' '1 Creamer'
 '1 DoubleDilla' '12 Tacos' 'Extra' '4 Lamp Chops' '3 Sandwiches'
 '2 Sandwiches' '1 Bun' '1 Crumb Cake' '1 Glazed Donut'
 '1 Glazed Old Fashioned Donut' '1 Old Fashioned Donut'
 '1 Boston Creme Donut' '1 Chocolate Covered Cake Donut'
 '1 Chocolate Frosted Sprinkle Donut' '1 Red Velvet Muffin'
 '1 Cinnamon Bun' '1 Cinnamon Twist' '1 Soft Pretzel'
 '1 Old Fashioned Chocolate Donut' '1 Cinnamon Raisin Bagel'
 '1 Everything Bagel' '1 Plain Bagel' '1 Sweet Cream Cheese Pretzel'
 '1 Jalapeno Stuffed Pretzel' '1 Wheat Shorti Roll' '1 Rainbow Cookie'
 '1 Tbs' '6 Strips' '10 Nuggets' 'Jr' '3/4 lb' 'Value Size' '6 Nuggets'
 '1/2 Size' '1 tsp' '1 tbsp' 'RT 44' '2 L' '1 Bagel Melt' 'Double'
 '2 tbsp' '1 Sandwich, Choose 2 Portion' '1 Rosette' '17"' 'Kid'
 '1 Hot Bowl' '3 L' '12 Breadsticks' 'Wacky Pack' 'Whole'
 '1/2 Dozen Breadsticks' '1 Pint' '1 Quart' '1 Medium Slice' '6 oz Cup'
 'Value' '4 Fingers' '3 Sliders; 2 Servings' '4-5 Servings'
 '4 Servings; Family Size' '1.5 L' 'Feeds 9-13' 'Per Slice'
 '12-17 Servings' 'Monster' '2 Slices; 2/16 Slices' '16"' '1 To Go Cup'
 '20-25 Servings' '1 Hoagie' '1 Sizzli' 'Kid Cup' 'Package' '1 Platter'
 '4 Crepes' '8-11 Servings' '20 Chicken Rings' '1 Pickle' 'Family Size'
 '6 Sticks' '2 tsp' '1 Dipper' '3 tbsp' '1 flatbread' '1.5 tbsp'
 '1 Banana Nut Muffin' 'Pint; Goblet' '1 Double'
 '1 Salad, Choose 2 Portion' '1 Pie' 'Magnum Bottle' '1 Dinner w/ Side'
 '1.25 L' '5 Chicken Tenders' '14 oz' '1 Shnack Wrap' '1 Small Slice'
 '2 Mozzarella Sticks' 'Serves 2-4' 'Extra Small' 'Full order' 'Adult'
 '1 Medium' 'XLarge' '1 pt' '3.25 oz Cup' 'Family Pack Max'
 '1 Egg Prepared' '1 Slab' '3 Hotcakes' '10 Fries'
 '1 Large Flatbread Slice' '8 Chicken Dippers' '1/2 order' 'Draft'
 '1 Plate Dinner' 'Togo Cup' 'Feeds 6-9' 'Family' '1 Tong' '1 Pattie'
 '1 Tin' 'Kids/Value' 'Family Pack Min' '1 Spoon' '2 Cod Fillets'
 '2 Hot Dogs' '1 Single' 'Full; Regular' '6 Pinwheels'
 'Combo Burrito Portion' '1 Small' 'Personal' '4 Piece' '2 Piece'
 '5 Servings' '4-8 Strips' '1/2 Pizza' '1 Thin' '1 Slider'
 '2 Corn Tortillas' '1 Flatbread Warmer Slice' '11 lb' '2 Cookies'
 '2 Sliders' '1 Twist' '3 Chicken Tenders' '1/2 gallon' '3 Servings'
 '12 Shwingz' '3 Shrimp' '12 Piesces' '2 Cinnabon Delights' '3 Ribs'
 '3 oz w/ Sauce' '6 Pot Stickers' 'Growler' '3 Twists' 'Single' '2 Cakes'
 '3 Mini Tacos' '1 Can' '1 Enchilada' 'Feeds 6-8' '3 Cubes' '4 Lamb Chops'
 '10 oz' '2 Chicken Tenders' '1 Plate' '2 Cobbs' '2 flatbreads'
 'Whole order' '1 Burrito Bowl' '1 Beet' '6 Piece; Medium'
 '8 Potato Halves' 'Pitcher' '1/2 Yard' '1 Serving; 3 Servings per Dish'
 '10-12 Servings' 'Little' '6 Shwingz' '1 Large' 'Regular Cup'
 '1 Apple Braid' '1/2 Dozen' '2 Stuffed French Toast' 'XL Pack Min'
 '1 Dog' '1/2 L' '1 Tray' '15 Count' 'One Bar' 'Picnic Pack Max'
 '4 Tortillas' '4 Drinks' '5 Fingers' '3 Fingers' 'Value Drink'
 '4 Sliders' '5 Onion Rings' '1 Small Piece' '2 Empanadas' 'Feeds 13+'
 'Feeds 5-6' '2 Bones w/ Rib Meat' '1 Ribeye' '4 Piece; Small' '9 Piece'
 '1 Hash Brown' '1 Dozen' '1 Small order' '4 Wings' '1 Mini Cake' '12 oz'
 '4 Pretzels' 'Box' '16 Sticks' '16 Piece; Family' 'Double Shot'
 'Snack Size' '1/9th Square' '1 Hashbrown' '6 Chicken Rings'
 '1 Chocolate Chocolate Chip Muffin' '12 Sticks' '1 slice' '1/4 order'
 '3 Chicken Rings' '2 Piece; Mini' 'A Lot' '7 lb' '1 Shmacker' '9 lb'
 '1 Slice; 1/8 Slices' '2 Stix' 'Feeds 4-5' '1/8th Slice'
 '6 Bagels, 1 Shmear Tub' '4 Chicken Tenders' '1 English Muffin'
 '4 Pieces of French Toast' 'Basket' 'cc scoop' '4 Chicken Nuggets'
 '1 Sauce Cup' '12 Cinnabon Delights' '4 Tomatoes' '2 Ea' '1 Fruit Cup'
 '13 Pieces' '5 Carrots' '3 Links' '10 Mozzarella Sticks'
 '13 Bagels, 2 Shmear Tubs' '2 Ribs' '5 Nuggets' '10 Count' 'Mega'
 'Quartino' '2 Rib Bones w/ Meat' '1 Package; Cup' '5 Mozzarella Sticks'
 '1/4' '9 Chicken Rings' '1 Large order' '1 Bran Muffin' '6-8 Servings'
 '8 Piece; Large' '1 Blueberry Muffin' '4 Cinnabon Delights' '1 Cookies'
 '1 Biscuit & Gravy' '12 Cookies' '4 Hotcakes' '9 Tenders' '20 Sticks'
 '3 Mozzarella Sticks' '3 Cookies' '9 Breadsticks']
*************************************


Calories
[  nan 190.  180.  ... 523.   64.1 786.2]
*************************************


Total_Fat
[       nan 6.0000e+00 4.0000e+00 5.0000e+00 2.5000e+00 2.8000e+01
 1.8000e+01 0.0000e+00 1.4000e+01 3.9000e+01 3.5000e+01 2.2000e+01
 7.0000e+00 4.5000e+00 1.2000e+01 9.0000e+00 3.3000e+01 3.1000e+01
 1.9000e+01 5.7000e+01 9.9000e+01 8.5000e+01 7.4000e+01 5.1000e+01
 6.3000e+01 4.3000e+01 2.3000e+01 2.0000e+01 1.1000e+01 1.0300e+02
 4.7000e+01 6.4000e+01 1.7000e+01 5.9000e+01 1.6000e+01 5.8000e+01
 2.5000e+01 1.3000e+01 3.7000e+01 6.2000e+01 8.3000e+01 6.6000e+01
 1.0200e+02 1.3700e+02 2.9000e+01 2.4000e+01 3.4000e+01 2.1000e+01
 5.2000e+01 7.8000e+01 4.4000e+01 1.5000e+00 1.0000e+00 3.2000e+01
 6.8000e+01 8.1000e+01 2.6000e+01 7.7000e+01 4.0000e+01 4.6000e+01
 9.8000e+01 6.0000e+01 5.0000e-01 2.0000e+00 7.0000e+01 4.2000e+01
 6.1000e+01 1.2200e+02 1.5000e+01 8.0000e+00 7.3000e+01 3.8000e+01
 1.0000e+01 9.6000e+01 7.1000e+01 4.9000e+01 2.7000e+01 3.5000e+00
 4.1000e+01 3.6000e+01 3.0000e+00 6.5000e+01 5.4000e+01 6.9000e+01
 4.5000e+01 5.5000e+01 5.0000e+01 6.7000e+01 4.8000e+01 3.0000e+01
 9.1000e+01 5.6000e+01 7.5000e+01 7.2000e+01 7.6000e+01 9.5000e+01
 8.2000e+01 2.1300e+02 1.4400e+02 7.9000e+01 2.5700e+02 5.3000e+01
 1.1800e+02 1.2500e+02 2.3900e+02 1.2000e+02 1.4000e+02 1.1600e+02
 8.7000e+01 9.7000e+01 8.0000e+01 8.9000e+01 9.2000e+01 8.6000e+01
 1.0000e-01 9.0000e+01 8.4000e+01 8.8000e+01 1.4400e+01 1.0700e+01
 3.1000e+00 4.0500e+01 3.4500e+01 1.1400e+01 2.3800e+01 2.4500e+01
 1.9400e+01 1.8600e+01 1.9500e+01 2.7400e+01 2.3500e+01 2.7500e+01
 1.1700e+01 1.9700e+01 3.6500e+01 3.5500e+01 2.9600e+01 1.6800e+01
 3.5200e+01 1.7000e+00 1.6500e+01 9.3000e+00 3.7000e+00 1.5800e+01
 2.5500e+01 1.5200e+01 1.2500e+01 2.2000e+00 7.8000e+00 3.0300e+01
 1.0100e+01 1.3200e+01 1.5500e+01 1.0200e+01 1.6600e+01 9.8000e+00
 1.0300e+01 1.2700e+01 7.4000e+00 8.1000e+00 9.2000e+00 9.6000e+00
 7.7000e+00 1.2100e+01 1.3900e+01 9.4000e+00 8.7000e+00 1.6300e+01
 1.5800e+02 1.0000e+02 1.0800e+02 9.3000e+01 1.2700e+02 1.0100e+02
 1.3000e+02 3.5000e+02 3.0000e+02 3.1000e+02 2.6000e+02 7.5000e+00
 5.5000e+00 2.8500e+01 1.3500e+01 1.1100e+02 1.8300e+02 2.1400e+02
 1.1500e+01 1.4500e+01 2.0500e+01 1.7500e+01 1.8500e+01 2.2500e+01
 2.1500e+01 9.4000e+01 1.8100e+02 1.8500e+02 1.8200e+02 1.8700e+02
 1.8800e+02 1.9100e+02 1.3500e+02 3.0800e+02 3.0600e+02 2.7500e+02
 1.5600e+02 3.6100e+02 3.5900e+02 1.4300e+02 3.2800e+02 1.4200e+02
 3.2500e+02 1.0700e+02 1.1700e+02 1.1400e+02 1.0900e+02 1.2400e+02
 1.2100e+02 1.1300e+02 1.3600e+02 1.6500e+02 1.0400e+02 1.3800e+02
 3.4500e+02 1.2900e+02 1.7200e+02 4.2900e+02 1.4900e+02 3.7200e+02
 2.3850e+01 1.6090e+01 1.5000e-01 6.3270e+01 4.6080e+01 5.5270e+01
 5.9480e+01 2.8460e+01 3.7980e+01 8.7320e+01 1.1780e+01 3.8990e+01
 3.8740e+01 1.1000e+02 8.5000e+00 9.5000e+00 4.2500e+01 1.0500e+01
 4.7500e+01 8.3500e+01 8.5500e+01 8.9500e+01 7.7500e+01 3.8500e+01
 4.5500e+01 4.6500e+01 4.9500e+01 2.9500e+01 4.8500e+01 8.0500e+01
 4.4500e+01 3.9500e+01 5.9500e+01 5.1500e+01 1.0250e+02 1.0500e+02
 5.2500e+01 1.0450e+02 5.4500e+01 5.3500e+01 2.6500e+01 8.6500e+01
 9.9500e+01 7.9500e+01 9.3500e+01 9.5500e+01 3.0500e+01 3.3500e+01
 5.5500e+01 6.5000e+00 1.2800e+02 6.0500e+01 8.1500e+01 5.8500e+01
 3.1800e+01 5.4300e+01 3.5150e+01 3.6150e+01 2.3300e+01 5.5300e+01
 3.1650e+01 1.9290e+01 1.3410e+01 5.3000e+02 1.6400e+02 1.7400e+02
 1.7300e+02 1.3400e+02 1.7100e+02 1.4800e+02 1.8600e+02 1.3100e+02
 2.0700e+02 1.0600e+02 1.3200e+02 2.1000e+02 2.1700e+02 1.5000e+02
 3.1800e+02 2.7700e+02 2.5800e+02 2.4900e+02 2.3100e+01 2.9800e+01
 1.5900e+01 2.8590e+01 2.4700e+01 5.1700e+01 4.7000e+00 5.9000e+00
 7.7400e+01 3.7500e+01 1.1800e+01 2.7300e+01 9.4800e+01 6.2400e+01
 9.9700e+01 5.7200e+01 3.6000e+00 3.2100e+01 2.1300e+01 2.1290e+01
 3.6300e+01 2.9770e+01 4.2700e+01 2.2200e+01 1.9100e+01 2.5400e+01
 3.4800e+01 1.0190e+01 2.8700e+01 1.8800e+01 1.0600e+01 2.1100e+01
 1.2180e+02 8.5200e+01 1.5600e+01 1.5470e+02 3.9000e+00 1.4990e+01
 1.0648e+02 2.3000e+00 3.4080e+01 1.9430e+01 3.8090e+01 3.3300e+01
 6.1350e+01 2.5300e+01 2.6900e+01 4.1400e+01 4.5880e+01 3.7480e+01
 3.4490e+01 3.4390e+01 4.5300e+01 2.5420e+01 4.3700e+01 6.7600e+01
 3.8880e+01 2.0400e+01 2.2300e+01 2.3400e+01 7.8700e+00 3.0510e+01
 4.9900e+01 7.1100e+01 6.4800e+00 5.0510e+01 4.9370e+01 3.0110e+01
 4.4370e+01 9.5900e+01 6.7910e+01 3.0330e+01 1.0870e+02 1.4490e+02
 7.2500e+01 1.7300e+01 7.2000e+00 2.8600e+01 8.6200e+00 1.0720e+01
 4.4200e+02 1.1500e+02 1.7000e+02 2.2700e+02 2.3100e+02 2.2600e+02
 3.5500e+02 3.6000e+02 3.5400e+02 1.4870e+02 1.6900e+01 1.3800e+01
 1.7900e+01 2.1200e+01 1.1600e+01 1.2800e+01 1.4800e+01 1.8200e+01
 4.6000e+00 1.1900e+01 1.3100e+01 1.0800e+01 1.9600e+01 1.7100e+01

 2.080e+02 3.730e+02 1.610e+02 2.040e+02 2.110e+02]
*************************************


Sodium_100g
[  nan   84.   79. ... 1012.  957.  825.]
*************************************


Potassium_100g
[ nan   1.   0.   2. 162. 166. 154. 171. 158. 198. 163. 186. 210. 160.
 183. 100. 229. 192. 138. 144. 262. 148. 155. 151. 145. 140. 146. 276.
 281. 412. 411. 408. 320. 199. 195. 203. 128. 250. 249. 110.  93. 280.
  77.  42. 429. 161.  71.  60. 214.  66. 278. 136. 147.  83. 111. 208.
  92. 149. 222. 168. 152. 401. 404. 417. 109.  88. 125. 167.  91.  36.
 180.  11.  17.  18.  16.  15.  61.  48.  53.  70. 194. 131. 127.  76.
  58. 361. 409. 224. 175.  37.  69. 206. 191. 182. 410. 185. 176. 212.
 118. 190. 257. 223. 248. 177. 117. 188. 179. 181. 123. 407. 105.  45.
 107. 286.  46. 226. 120. 296. 200.  49.  59.  56.  29.  57.  74.  50.
  35.  43.  78.  54. 129.  99. 435. 104. 319.  27.  97. 293.  79. 219.
 102. 316. 389.  26. 368. 246. 400. 495. 372. 446. 211.  68.  95. 561.
 343. 106. 386.  96.  89. 340. 244. 234. 228. 480. 116. 556.  12. 241.
 247. 115. 112.   8.  62. 359. 132. 139. 221.  44. 150. 225.  28.  67.
 156.  64.  94.  47. 178. 335. 207. 279. 282. 297. 205. 321. 209. 119.]
*************************************


Carbohydrates_100g
[     nan 1.50e+01 1.60e+01 2.10e+01 5.00e+00 8.00e+00 2.40e+01 2.50e+01
 1.70e+01 2.70e+01 1.30e+01 2.00e+01 1.40e+01 1.80e+01 2.30e+01 7.00e+00
 2.80e+01 3.80e+01 2.60e+01 3.20e+01 3.30e+01 9.00e+00 1.90e+01 5.40e+01
 5.10e+01 3.00e+00 2.20e+01 2.90e+01 3.90e+01 0.00e+00 1.20e+01 1.10e+01
 3.00e+01 4.40e+01 6.30e+01 6.70e+01 4.50e+01 5.60e+01 5.80e+01 5.70e+01
 6.20e+01 5.90e+01 6.00e+01 5.30e+01 5.20e+01 5.50e+01 1.00e+01 8.00e+01
 7.50e+01 4.60e+01 3.40e+01 4.10e+01 4.20e+01 4.00e+01 3.70e+01 7.10e+01
 3.50e+01 4.30e+01 3.10e+01 6.80e+01 7.00e+01 4.80e+01 6.50e+01 6.00e+00
 1.00e+00 3.60e+01 4.70e+01 4.00e+00 7.30e+01 6.40e+01 6.10e+01 6.60e+01
 2.00e+00 3.70e+02 2.03e+02 8.30e+01 8.60e+01 1.06e+02 7.40e+01 4.90e+01
 1.11e+02 1.14e+02 5.00e+01 8.20e+01 7.70e+01 6.90e+01 8.10e+01 7.60e+01
 1.80e+03 7.80e+01 8.80e+01 9.90e+01 9.00e+01 8.40e+01 1.00e+02 8.90e+01
 9.20e+01 9.50e+01 7.20e+01 8.50e+01 6.67e+02 7.90e+01 1.07e+02 9.40e+01
 6.13e+02 1.71e+02 1.88e+02 5.00e+02 4.00e+02 1.38e+02 1.24e+02]
*************************************


Protein_100g
[ nan   1.   0.   8.   7.  10.  12.  14.  15.  16.  13.  11.   4.   2.
   3.   9.  18.   5.   6.  32.  19.  23.  22.  26.  24.  27.  21.  17.
  20.  28.  35.  34.  33.  25.  29.  40.  31.  49.  30.  45.  42.  43.
  41.  39.  48.  71.  36. 141.  38.  44. 157.  60. 100.  55. 133.  99.
  37. 425.  92.  63.]
*************************************


Sugar_100g
[     nan 1.00e+01 1.10e+01 1.20e+01 3.00e+00 1.00e+00 2.00e+00 4.00e+00
 0.00e+00 5.00e+00 9.00e+00 1.60e+01 1.40e+01 2.10e+01 2.20e+01 5.40e+01
 3.00e+01 3.10e+01 1.30e+01 2.90e+01 1.90e+01 2.00e+01 1.80e+01 6.00e+00
 2.80e+01 3.30e+01 3.50e+01 7.00e+00 8.00e+00 1.70e+01 4.80e+01 8.00e+01
 2.60e+01 6.00e+01 2.70e+01 2.50e+01 2.30e+01 1.50e+01 2.40e+01 3.20e+01
 3.80e+01 4.10e+01 4.30e+01 3.40e+01 5.60e+01 6.70e+01 3.60e+01 4.40e+01
 5.00e+01 3.70e+01 3.90e+01 4.20e+01 3.50e+02 6.30e+01 4.00e+01 6.80e+01
 6.60e+01 7.80e+01 5.30e+01 4.90e+01 7.10e+01 5.90e+01 5.70e+01 6.10e+01
 7.90e+01 5.80e+01 1.80e+03 7.60e+01 9.90e+01 8.80e+01 4.60e+01 5.20e+01
 4.70e+01 8.30e+01 4.50e+01 6.20e+01 7.00e+01 9.20e+01 5.50e+01 9.30e+01
 7.40e+01 3.70e+02 6.40e+01 5.10e+01 1.00e+02 8.10e+01 7.20e+01 1.58e+02
 5.46e+02 7.50e+01 4.61e+02 1.25e+02 1.09e+02]
*************************************


Dietary_Fiber_100g
[ nan   0.   1.   2.   4.   3.   5.  14.  11.   7.   9.   8.   6.  15.
  39.  10.  12.  13.  18.  17.  25.  26.  32.  19.  63. 100.  49. 400.
  21.]
*************************************


Calories_text
[nan '0-170' '2170-2300' '100-110' '580-720' '1740-2160' '190-200'
 '380-400' '1020-1040' '1000-1010' '1130-1710' '710-1130' '890-1350'
 '50-60' '630-850' '0-60' '95-180' '130-156' '760-980' '1140-1470' '0-115'
 '430-580' '20-90' '25-65' "'10-25" "'5-30" "'4-12" '1475-2605'
 '2950-4360' '430-520' '0-5' '25-85' "'5-10" '740-960' '930-1150'
 '1150-1370' '1000-1220' '520-650' '660-880' '440-570' '960-1180'
 '470-600' '480-610' '870-1090' '670-890' '650-870' '290-420' '3480-3720'
 '750-970' '720-940' '1230-1390' '1220-1380' '880-1040' '810-1030'
 '970-1280' '980-1140' '4500-4620' '530-660' '0-155' '850-1100' '0-130'
 "'5-50" '90-360' '43-173' '20-82' '40-160' '20-80' '65-260' '39-157'
 '30-120' '60-241' '970-1000' '445-770' '400-750' '80-100' '0-80'
 '272-319' '282-337' '294-319' '334-360' '243-251' '236-252' '450-475'
 '860-1215' '700-970' '150-835' '110-550' '220-1520' '790-1090'
 '2320-2520' '<5' '640-1270' '830-1140' '30-70' "'5-130" '550-830'
 '450-900' '460-740' '0-280' '630-930' '480-900' '720-1180' '780-1220'
 '450-870' '430-710' '640-920' '650-950' '490-500' '1670-3750' '770-1050'
 '2310-2430' '550-570' '1260-1560' '1160-1580' '495-765' '950-1250'
 '1190-1490' '430-560' '67-266' '0-440' '500-980' "'3-10" '1160-1360'
 '1270-1470' '340-880' '1420-1840' '920-1150' '0-20' '740-1040' '780-1080'
 '0-200' '310-600' '590-860' '1260-1460' '480-590' '3960-4080' '630-900'
 '1010-1430' '345-705' '1300-1580' '1040-1340' '360-430' '800-1100'
 '720-1280' '1350-1770' '1270-1690' '1000-1420' '950-1150' '780-830'
 '900-1090' '900-1100' '1250-1450' '630-830' '770-1060' '400-710'
 '870-1290' '750-950' '220-420' '770-1200' '870-1170' '730-780' '390-690'
 '1350-1550' '110-130' '780-1060' '750-1050' '1050-1250' '1130-1430'
 '480-600' '1190-1390' '740-940' '740-1130' '660-860' '1380-2870'
 '290-410' '1350-1650' '1190-1610' '990-1320' '1270-1570' '710-970'
 '870-1070' '860-1160' '980-1210' '580-710' '660-960' '340-830' '330-630'
 '470-590' '890-1310' '450-710' '1060-1360' '1240-1660' '1010-1310'
 '630-1250' '340-1175' '475-705' '1020-1220' '980-1280' '730-1030'
 '440-760' '1010-1210' '720-990' '670-870' '80-320' '90-110' '840-1140'
 '810-1010' '4560-4680' '930-1350' '750-1170' '230-1110' '1090-1390'
 '980-1180' '730-930' '730-1150' '290-670' '920-1220' '900-1190' '370-460'
 '760-880' '490-610' '660-1080' '960-1160' '1030-1450' '1260-1680'
 '850-1150' '420-860' '880-1180' '490-850' '1210-1630' '410-850'
 '470-1160' '1280-1700' '1030-1320' '650-890' '430-845' '1070-1490'
 '770-970' '3480-3600']
*************************************


Total_Fat_text
[nan '119-131' '52-55' '73-76' '23-33' '65-68' '71-74' '85-88' '68-100'
 "'9-10" '38-41' '60-63' '44-103' '25-73' '68-70' '54-57' '40-88' '90-93'
 '99-102' '82-85' '91-94' '46-49' '63-66' '68-71' '59-62' '61-64' '67-70'
 '34-44' '51-66' '17-41' "'7-28" '0-1' "'1-4" "'3-10" '7.5-30' "'1-5"
 '40-43' '14-43' '3.5-5' '4.3-15.4' '11.4-16.4' '13-17.4' '7.1-12'
 "'11-14" '20.8-25.3' '23-24' '41-82' '43-77' "'3-12" '0-8' '0-140'
 '18-36' '17-37' "'7-29" "'5-7" '51-63' '37-73' '19-20' '34-42' '34-54']
*************************************


Saturated_Fat_text
[nan '38-39' '31-32' "'10-17" '30-51' "'8-9" "'10-12" '13-33' "'6-23"
 '22-23' '21-22' "'12-32" '35-36' '37-38' '16-17' '18-19' '23-24' '24-25'
 '14-18' '21-27' "'9-19" "'2-8" "'1-1" "'1-3" "'1-4" "'1-9" "'1-2"
 '1.8-7.9' '6.2-7.9' '7.1-8.8' '3.7-5.9' '4.9-6.1' '8.5-10.2' '14-27'
 '0-1' '0-3' "'6-18" "'2-3" '18-27' '13-26' "'12-18" "'9-12.5"]
*************************************


Trans_Fat_text
[nan '0-1' '1.5-3' "'7-15" "'1-6" "'1-3" "'1-2" "'2-8"]
*************************************


Cholesterol_text
[nan '302-306' '43-63' '128-189' '30-35' '60-70' '523-1014' '303-370'
 '605-688' '<5' '40-70' '60-105' '45-110' "'1-4" "'3-13" '160-175'
 '120-190' "'10-15" '10.3-37.8' '36-44' '41.2-46.6' '22-33' '30.1-33.6'
 '<1' '35-95' "'1-2" '75-120' '75-150' '50-80']
*************************************


Sodium_text
[nan '40-80' '5450-6770' '270-290' '2490-2550' '3030-3090' '250-740'
 '2740-2800' '2890-2950' '3330-3390' '3290-3350' '750-2220' '50-60'
 '110-120' '3910-3970' '1990-2010' '1390-1400' '2920-2980' '2110-2950'
 '1610-2050' '3740-3800' '4160-4220' '2780-2840' '1770-2340' '4170-4230'
 '4080-4140' '3480-3540' '4300-4360' '1560-1620' '2430-2490' '2280-2340'
 '2560-2620' '5420-5480' '1790-1850' '3490-3550' '4060-4120' '1720-2220'
 '2580-3330' "'1-30" '1270-1420' '1280-1300' "'6-50" "'6-45" '0-55'
 '14-55' '24-98' "'3-11" "'10-39" "'5-20" '53-210' '110-440' "'1-5"
 "'3-10" '67-268' '2570-2750' '615-1130' '155-260' '0-35' '555.8-843'
 '666-836' '555.8-798.5' '774.4-801.9' '486-637' '488.8-506.8'
 '941.1-968.3' '<5' '2360-4280' '2240-4260' '120-640' '60-85' '0-320'
 '1800-3600' '1180-1230' '1320-1500' '71-285' "'5-80" '180-280'
 '2340-3750' '2250-4060' '30-35' '120-130' '1500-1620' '1630-2430']
*************************************


Potassium_text
[nan '450-470' '<1']
*************************************


Carbohydrates_text
[nan '0-47' '192-224' "'10-13" '95-101' '96-102' '68-108' '97-103'
 '98-104' '112-118' '99-105' '204-325' '50-60' '48-51' '144-150' '61-64'
 '53-56' '87-93' '137-139' '103-109' '174-180' '92-98' '85-34' "'10-14"
 '125-131' '105-111' '107-113' '94-100' '89-95' '80-86' '86-92' '80-106'
 '120-159' '0-30' '36-58' '66-67' '<1' "'1-39" "'1-35" "'7-27" "'10-41"
 "'5-19" "'8-32" "'10-40" "'4-18" "'10-39" "'7-28" '55-59' '33-46' "'8-10"
 '0-1' '0-25' '7.8-15.3' '14.7-16.6' '7.8-14.3' '34.2-37.3' '9.4-11.7'
 '21.7-24' '44.6-47.7' '23-45' '43-77' "'2-12" '0-7' '20-39' '35-39'
 "'3-13" "'1-2" '0-55' "'5-6" "'1-5" '0-2' '42-57' '51-101' '43-64'
 '28-38' '38-41']
*************************************


Protein_text
[nan '84-85' '43-45' '59-60' "'7-10" '50-51' '49-50' '55-56' '21-30'
 "'2-4" "'5-7" '54-55' '58-59' '40-42' '38-57' '27-33' '65-66' '63-64'
 '73-74' '39-49' '74-75' '70-71' '67-68' '79-80' '30-31' '31-33' '25-26'
 '45-47' '29-31' '35-37' '71-72' '32-36' '48-54' "'5-21" '39-41' '<1'
 '0-1' '0-2' "'1-2" '3.5-14' "'1-5" '96-98' '39-50' "'4-6" '30.5-31.5'
 '30.6-31' '20.8-23.7' "'3-13" "'10-40" "'10-39" "'12-13" "'8-32" '87-132'
 "'10-41" '25-50' '58-88' "'7-28" "'5-19" "'3-24"]
*************************************


Sugar_text
[nan '0-47' '34-65' "'3-5" '49-85' '146-254' '20-23' '41-47' "'9-11"
 '49-51' "'5-6" "'5-14" "'8-11" "'4-30" "'6-45" '0-30' "'5-8" "'7-10" '<1'
 '0-41' "'1-30" "'6-26" "'8-30" "'5-19" "'6-25" "'5-18" "'6-22" "'2-8"
 "'7-26" "'6-24" "'7-27" '0-1' "'1-2" '0-25' "'8-9" "'5-17" "'1-6" '0-55'
 '18-21' "'2-3" "'6-42" '19-38' "'3-28" '40-61' "'4-28" "'2-35"]
*************************************


Dietary_Fiber_text
[nan '19-20' "'8-9" "'1-4" "'7-8" "'2-12" '0-1' '0-2' "'10-12" "'5-6"
 "'8-10" "'9-11" "'6-8" "'1-2" "'11-12" "'10-11" "'7-9" "'6-7" "'9-12"
 "'4-5" '<1' '<8' '<1-1' "'2-4" '0-5' '0-3' "'2-5" "'2-3" '<1-4' '-1'
 "'6-9" "'4-6" '0-30']
*************************************


Kids_Meal
[0 1]
*************************************


Limited_Time_Offer
[0 1]
*************************************


Regional
[0 1]
*************************************


Shareable
[0 1]
*************************************

In [10]:
# for each column
for col in cols:
    print(col)

    # get a list of unique values
    unique = df[col].unique()

    # if number of unique values is less than 30, print the values. Otherwise print the number of unique values
    if len(unique)<30:
        print(unique, '\n====================================\n\n')
    else:
        print(str(len(unique)) + ' unique values', '\n====================================\n\n')

Menu_Item_ID
44936 unique values
====================================


Year
[2017 2018]
====================================


Restaurant_Item_Name
51660 unique values
====================================


restaurant
96 unique values
====================================


Restaurant_ID
94 unique values
====================================


Item_Name
46995 unique values
====================================


Item_Description
62859 unique values
====================================


Food_Category
['Beverages' 'Entrees' 'Pizza' 'Sandwiches' 'Burgers' 'Salads'
 'Appetizers & Sides' 'Baked Goods' 'Desserts' 'Soup'
 'Toppings & Ingredients' 'Fried Potatoes']
====================================


Serving_Size
1164 unique values
====================================


Serving_Size_text
[nan "'5-6" '18-25' "'12-20" '16-24' '10.98-11.00' '14.00-56.00'
 '7.00-28.00' '14.00-54.00' '138-139' '12.00-20.00' '620.00-1350.00' 'oz'
 '5.00-6.00' '16.00-24.00' '300.00-680.00']
====================================


Serving_Size_Unit
[nan 'fl oz' 'g' 'oz' 'ml']
====================================


Serving_Size_household
816 unique values
====================================


Calories
1348 unique values
====================================


Total_Fat
613 unique values
====================================


Saturated_Fat
391 unique values
====================================


Trans_Fat
98 unique values
====================================


Cholesterol
766 unique values
====================================


Sodium
2428 unique values
====================================


Potassium
196 unique values
====================================


Carbohydrates
718 unique values
====================================


Protein
509 unique values
====================================


Sugar
461 unique values
====================================


Dietary_Fiber
167 unique values
====================================


Calories_100g
596 unique values
====================================


Total_Fat_100g
94 unique values
====================================


Saturated_Fat_100g
48 unique values
====================================


Trans_Fat_100g
[nan  0.  1.  7.  4.  3.  2. 14. 16.  5. 10. 18.  6. 17. 53.  8.  9.]
====================================


Cholesterol_100g
264 unique values
====================================


Sodium_100g
1392 unique values
====================================


Potassium_100g
196 unique values
====================================


Carbohydrates_100g
111 unique values
====================================


Protein_100g
60 unique values
====================================


Sugar_100g
93 unique values
====================================


Dietary_Fiber_100g
[ nan   0.   1.   2.   4.   3.   5.  14.  11.   7.   9.   8.   6.  15.
  39.  10.  12.  13.  18.  17.  25.  26.  32.  19.  63. 100.  49. 400.
  21.]
====================================


Calories_text
239 unique values
====================================


Total_Fat_text
60 unique values
====================================


Saturated_Fat_text
42 unique values
====================================


Trans_Fat_text
[nan '0-1' '1.5-3' "'7-15" "'1-6" "'1-3" "'1-2" "'2-8"]
====================================


Cholesterol_text
[nan '302-306' '43-63' '128-189' '30-35' '60-70' '523-1014' '303-370'
 '605-688' '<5' '40-70' '60-105' '45-110' "'1-4" "'3-13" '160-175'
 '120-190' "'10-15" '10.3-37.8' '36-44' '41.2-46.6' '22-33' '30.1-33.6'
 '<1' '35-95' "'1-2" '75-120' '75-150' '50-80']
====================================


Sodium_text
83 unique values
====================================


Potassium_text
[nan '450-470' '<1']
====================================


Carbohydrates_text
76 unique values
====================================


Protein_text
59 unique values
====================================


Sugar_text
46 unique values
====================================


Dietary_Fiber_text
33 unique values
====================================


Kids_Meal
[0 1]
====================================


Limited_Time_Offer
[0 1]
====================================


Regional
[0 1]
====================================


Shareable
[0 1]
====================================

##  The number of missing values of each column.

In [11]:
df.isnull().sum()

Menu_Item_ID                  0
Year                          0
Restaurant_Item_Name          0
restaurant                    0
Restaurant_ID                 0
Item_Name                     0
Item_Description              0
Food_Category                 0
Serving_Size              38320
Serving_Size_text         65180
Serving_Size_Unit         38292
Serving_Size_household    49981
Calories                   9904
Total_Fat                 10373
Saturated_Fat             11076
Trans_Fat                 13716
Cholesterol               12000
Sodium                    10228
Potassium                 64121
Carbohydrates             10931
Protein                   10986
Sugar                     12288
Dietary_Fiber             11779
Calories_100g             39341
Total_Fat_100g            39533
Saturated_Fat_100g        39934
Trans_Fat_100g            41391
Cholesterol_100g          40093
Sodium_100g               39366
Potassium_100g            64596
Carbohydrates_100g        39627
Protein_100g              39688
Sugar_100g                40012
Dietary_Fiber_100g        39828
Calories_text             64916
Total_Fat_text            65150
Saturated_Fat_text        65169
Trans_Fat_text            65209
Cholesterol_text          64861
Sodium_text               65126
Potassium_text            65217
Carbohydrates_text        64585
Protein_text              64752
Sugar_text                64628
Dietary_Fiber_text        64408
Kids_Meal                     0
Limited_Time_Offer            0
Regional                      0
Shareable                     0
dtype: int64

In [12]:
df.describe() # for numeric columns

,Menu_Item_ID,Year,Restaurant_ID,Serving_Size,Calories,Total_Fat,Saturated_Fat,Trans_Fat,Cholesterol,Sodium,...,Sodium_100g,Potassium_100g,Carbohydrates_100g,Protein_100g,Sugar_100g,Dietary_Fiber_100g,Kids_Meal,Limited_Time_Offer,Regional,Shareable
count,65219.000000,65219.000000,65219.000000,26899.000000,55315.000000,54846.000000,54143.000000,51503.000000,53219.000000,54991.000000,...,25853.000000,623.000000,25592.000000,25531.00000,25207.000000,25391.000000,65219.000000,65219.000000,65219.000000,65219.000000
mean,103164.326117,2017.461829,53.060151,92.222657,380.020880,17.237539,6.488704,0.300858,56.726642,686.570538,...,292.044482,134.134831,15.033565,4.53719,7.602095,0.676145,0.057621,0.032445,0.031969,0.028642
std,60360.317220,0.498545,27.108196,172.826444,420.620976,25.461848,13.354115,10.957444,105.439070,1063.799544,...,1448.304081,119.938038,20.082218,6.94306,15.596987,2.964487,0.233028,0.177179,0.175919,0.166799
min,7.000000,2017.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39361.500000,2017.000000,30.000000,12.000000,130.000000,0.500000,0.000000,0.000000,0.000000,80.000000,...,12.000000,37.000000,6.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,122345.000000,2017.000000,56.000000,24.000000,270.000000,9.000000,3.500000,0.000000,20.000000,310.000000,...,60.000000,117.000000,12.000000,2.00000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,156752.500000,2018.000000,79.000000,98.000000,500.000000,23.000000,9.000000,0.000000,69.000000,930.000000,...,475.000000,198.000000,19.000000,7.00000,11.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,179840.000000,2018.000000,94.000000,3792.000000,13960.000000,1078.000000,2046.000000,1470.000000,2680.000000,41290.000000,...,209000.000000,561.000000,1800.000000,425.00000,1800.000000,400.000000,1.000000,1.000000,1.000000,1.000000

In [13]:
df.describe(include='object')  # for object columns

,Restaurant_Item_Name,restaurant,Item_Name,Item_Description,Food_Category,Serving_Size_text,Serving_Size_Unit,Serving_Size_household,Calories_text,Total_Fat_text,Saturated_Fat_text,Trans_Fat_text,Cholesterol_text,Sodium_text,Potassium_text,Carbohydrates_text,Protein_text,Sugar_text,Dietary_Fiber_text
count,65219,65219,65219,65219,65219,39,26927,15238,303,69,50,10,358,93,2,634,467,591,811
unique,51660,96,46995,62859,12,15,4,815,238,59,41,7,28,82,2,75,58,45,32
top,"Jack in the Box Fruitwater Fizzy Cherry Lime, ...",Starbucks,Diet Coke,"Chocolate Chip Cookie, Desserts",Beverages,14.00-56.00,g,1 Slice,<5,68-70,'1-3,'1-3,<5,14-55,450-470,<1,<1,<1,<1
freq,4,4504,42,10,23396,17,10843,1704,17,3,3,3,325,2,1,553,406,536,749

In [14]:
df.describe(include='all')  # for both object and numeric data

,Menu_Item_ID,Year,Restaurant_Item_Name,restaurant,Restaurant_ID,Item_Name,Item_Description,Food_Category,Serving_Size,Serving_Size_text,...,Sodium_text,Potassium_text,Carbohydrates_text,Protein_text,Sugar_text,Dietary_Fiber_text,Kids_Meal,Limited_Time_Offer,Regional,Shareable
count,65219.000000,65219.000000,65219,65219,65219.000000,65219,65219,65219,26899.000000,39,...,93,2,634,467,591,811,65219.000000,65219.000000,65219.000000,65219.000000
unique,NaN,NaN,51660,96,NaN,46995,62859,12,NaN,15,...,82,2,75,58,45,32,NaN,NaN,NaN,NaN
top,NaN,NaN,"Jack in the Box Fruitwater Fizzy Cherry Lime, ...",Starbucks,NaN,Diet Coke,"Chocolate Chip Cookie, Desserts",Beverages,NaN,14.00-56.00,...,14-55,450-470,<1,<1,<1,<1,NaN,NaN,NaN,NaN
freq,NaN,NaN,4,4504,NaN,42,10,23396,NaN,17,...,2,1,553,406,536,749,NaN,NaN,NaN,NaN
mean,103164.326117,2017.461829,NaN,NaN,53.060151,NaN,NaN,NaN,92.222657,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.057621,0.032445,0.031969,0.028642
std,60360.317220,0.498545,NaN,NaN,27.108196,NaN,NaN,NaN,172.826444,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.233028,0.177179,0.175919,0.166799
min,7.000000,2017.000000,NaN,NaN,1.000000,NaN,NaN,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
25%,39361.500000,2017.000000,NaN,NaN,30.000000,NaN,NaN,NaN,12.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
50%,122345.000000,2017.000000,NaN,NaN,56.000000,NaN,NaN,NaN,24.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
75%,156752.500000,2018.000000,NaN,NaN,79.000000,NaN,NaN,NaN,98.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
max,179840.000000,2018.000000,NaN,NaN,94.000000,NaN,NaN,NaN,3792.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000

## Frequency distribution for each column

In [15]:
for col in cols:
    print(col)
    value_counts = df[col].value_counts()
    print(value_counts, '\n\n=======================================================')

Menu_Item_ID
19067     2
45721     2
45760     2
45754     2
45741     2
         ..
156586    1
156584    1
156581    1
140791    1
174902    1
Name: Menu_Item_ID, Length: 44936, dtype: int64

=======================================================
Year
2017    35099
2018    30120
Name: Year, dtype: int64

=======================================================
Restaurant_Item_Name
Jack in the Box Fruitwater Fizzy Cherry Lime, Lemonade, Lemon Lime, Mixed Berry, Peach Lemonade or S    4
Jack in the Box POWERade Zero Cherry, Fruit Punch, Grape, Lemon, Lime, Orange, Raspberry or Strawber    4
Jack in the Box Fanta Zero Cherry, Fruit Punch, Grape, Lime, Orange, Peach, Raspberry or Strawberry,    4
Jack in the Box Hi C Cherry, Fruit Punch, Grape, Lemon, Orange, Orange Vanilla, Raspberry, Raspberry    4
BJ's Restaurant & Brewhouse BJs Signature Five Cheese Blend, for 1 Topping Build Your Own Deep Dish     4
                                                                                                       ..
Red Lobster Shrimp & Wood Grilled Chicken w/ Hand Breaded Shrimp                                        1
Red Lobster Shrimp & Wood Grilled Chicken w/ Wood Grilled Shrimp Skewer                                 1
Red Lobster Broiled Fish, Kids                                                                          1
Red Lobster Seaport Lobster & Shrimp                                                                    1
LongHorn Steakhouse Whiskey Smash                                                                       1
Name: Restaurant_Item_Name, Length: 51660, dtype: int64

=======================================================
restaurant
Starbucks          4504
Dunkin' Donuts     3707
Wawa               2685
Sheetz             2429
Sonic              1605
                   ...
Chipotle            146
Ci Ci's Pizza       130
Five Guys           115
Little Caesars      108
In-N-Out Burger      93
Name: restaurant, Length: 96, dtype: int64

=======================================================
Restaurant_ID
80    4504
30    3707
87    2685
78    2429
79    1605
      ...
21     146
24     130
35     115
51     108
41      93
Name: Restaurant_ID, Length: 94, dtype: int64

=======================================================
Item_Name
Diet Coke                                      42
Sprite                                         39
Coffee                                         38
Dr Pepper                                      36
Caesar Salad                                   32
                                               ..
Skinny Absolutely Absolut Freckled Lemonade     1
Pretzel Bites w/ Beer Cheese Dip                1
Jump Starter Fresh Fried Zucchini Sticks        1
Carrots, Kids                                   1
Whiskey Smash                                   1
Name: Item_Name, Length: 46995, dtype: int64

=======================================================
Item_Description
Chocolate Chip Cookie, Desserts                                                                                                      10
Sausage Biscuit, Breakfast                                                                                                            9
Bottled Water, Drinks                                                                                                                 7
Biscuit, Breakfast                                                                                                                    7
Hash Browns, Breakfast                                                                                                                6
                                                                                                                                     ..
Spicy Monterey w/ Turkey, Ham, Mozzarella, Pickles, Lettuce, Tomatoes, Mayo & Four Pepper Chili Sauce, Deli Classics, 8 in            1
Spicy Monterey w/ Turkey, Ham, Mozzarella, Pickles, Lettuce, Tomatoes, Mayo & Four Pepper Chili Sauce, Deli Classics, 12 in           1
Mesquite w/ Bacon, Cheddar, Lettuce, Tomatoes, Onions & Ranch, Chicken Subs, 4 in                                                     1
Spicy Monterey on Flatbread w/ Turkey, Ham, Mozzarella, Pickles, Lettuce, Tomatoes, Mayo & Four Pepper Chili Sauce, Deli Classics     1
Street Tacos in 2 Tortillas w/ Carne Asada Steak, Chili Salsa, Onions, Cilantro & Avocado, Tacos & Tostadas                           1
Name: Item_Description, Length: 62859, dtype: int64

=======================================================
Food_Category
Beverages                 23396
Toppings & Ingredients    10153
Entrees                    7579
Sandwiches                 6391
Appetizers & Sides         4123
Pizza                      3373
Desserts                   3016
Baked Goods                1908
Salads                     1807
Burgers                    1558
Soup                       1175
Fried Potatoes              740
Name: Food_Category, dtype: int64

=======================================================
Serving_Size
16.00     2976
12.00     2711
24.00     1562
20.00     1477
32.00      963
          ...
1.23         1
3.04         1
0.85         1
0.73         1
547.00       1
Name: Serving_Size, Length: 1163, dtype: int64

=======================================================
Serving_Size_text
14.00-56.00       17
oz                 5
'12-20             2
7.00-28.00         2
14.00-54.00        2
12.00-20.00        2
'5-6               1
18-25              1
16-24              1
10.98-11.00        1
138-139            1
620.00-1350.00     1
5.00-6.00          1
16.00-24.00        1
300.00-680.00      1
Name: Serving_Size_text, dtype: int64

=======================================================
Serving_Size_Unit
g        10843
fl oz    10099
oz        5941
ml          44
Name: Serving_Size_Unit, dtype: int64

=======================================================
Serving_Size_household
1 Slice                          1704
1 Sandwich                        515
Large                             499
Small                             492
Medium                            431
                                 ...
2 Mini Cannoli                      1
2 Chops                             1
2 tsp                               1
5 Pieces, 4 Servings per Dish       1
9 Breadsticks                       1
Name: Serving_Size_household, Length: 815, dtype: int64

=======================================================
Calories
0.0       2355
170.0     1085
150.0     1071
160.0     1044
240.0     1005
          ...
872.0        1
544.0        1
1109.0       1
472.0        1
786.2        1
Name: Calories, Length: 1347, dtype: int64

=======================================================
Total_Fat
0.00     13688
6.00      1500
9.00      1443
8.00      1429
10.00     1364
         ...
21.90        1
10.40        1
28.46        1
59.48        1
31.10        1
Name: Total_Fat, Length: 612, dtype: int64

=======================================================
Saturated_Fat
0.00     16487
6.00      2459
5.00      2294
7.00      2225
1.00      2065
         ...
6.04         1
5.38         1
21.55        1
30.99        1
15.70        1
Name: Saturated_Fat, Length: 390, dtype: int64

=======================================================
Trans_Fat
0.00     43748
1.00      2701
0.50      2340
1.50       940
2.00       706
         ...
0.53         1
3.04         1
1.71         1
0.98         1
43.80        1
Name: Trans_Fat, Length: 97, dtype: int64

=======================================================
Cholesterol
0.0      19111
10.0      2013
20.0      1898
15.0      1888
5.0       1876
         ...
13.1         1
141.8        1
213.7        1
73.5         1
3.6          1
Name: Cholesterol, Length: 765, dtype: int64

=======================================================
Sodium
0.0       3602
10.0      1425
15.0       909
5.0        878
20.0       705
          ...
931.9        1
435.3        1
482.5        1
973.2        1
2044.0       1
Name: Sodium, Length: 2427, dtype: int64

=======================================================
Potassium
0.0      218
50.0      41
35.0      30
15.0      29
10.0      26
        ...
171.0      1
231.0      1
377.0      1
24.0       1
950.0      1
Name: Potassium, Length: 195, dtype: int64

=======================================================
Carbohydrates
0.0      4137
1.0      2002
2.0      1676
3.0      1161
4.0       910
         ...
30.6        1
45.8        1
209.7       1
165.6       1
293.0       1
Name: Carbohydrates, Length: 717, dtype: int64

=======================================================
Protein
0.00     12689
1.00      2923
2.00      2519
3.00      2457
4.00      2082
         ...
32.90        1
21.95        1
6.84         1
71.49        1
7.50         1
Name: Protein, Length: 508, dtype: int64

=======================================================
Sugar
0.0      9561
2.0      3647
1.0      3314
3.0      2789
4.0      2315
         ...
5.3         1
20.2        1
161.8       1
3.6         1
17.7        1
Name: Sugar, Length: 460, dtype: int64

=======================================================
Dietary_Fiber
0.00     23384
1.00      8832
2.00      6769
3.00      3883
4.00      2823
         ...
9.40         1
6.11         1
4.30         1
14.30        1
12.60        1
Name: Dietary_Fiber, Length: 166, dtype: int64

=======================================================
Calories_100g
0.0      1408
44.0      527
1.0       428
53.0      359
49.0      350
         ...
561.0       1
594.0       1
688.0       1
454.0       1
445.0       1
Name: Calories_100g, Length: 595, dtype: int64

=======================================================
Total_Fat_100g
0.0      9228
1.0      2066
2.0      1869
3.0      1220
4.0      1011
         ...
204.0       1
129.0       1
182.0       1
74.0        1
106.0       1
Name: Total_Fat_100g, Length: 93, dtype: int64

=======================================================
Saturated_Fat_100g
0.0      10756
1.0       3265
2.0       2913
3.0       1856
4.0       1548
5.0       1236
6.0        878
7.0        710
8.0        487
9.0        331
11.0       292
10.0       211
12.0       132
13.0       128
14.0       127
18.0        98
17.0        71
21.0        45
19.0        43
16.0        41
15.0        38
20.0        17
22.0        10
25.0         7
30.0         5
23.0         4
24.0         4
27.0         3
26.0         3
50.0         3
35.0         2
29.0         2
49.0         2
31.0         2
56.0         2
100.0        2
141.0        1
43.0         1
572.0        1
59.0         1
32.0         1
33.0         1
104.0        1
40.0         1
38.0         1
39.0         1
28.0         1
Name: Saturated_Fat_100g, dtype: int64

=======================================================
Trans_Fat_100g
0.0     23111
1.0       564
2.0        87
3.0        24
4.0        22
5.0         3
18.0        3
53.0        3
7.0         2
14.0        2
6.0         2
16.0        1
10.0        1
17.0        1
8.0         1
9.0         1
Name: Trans_Fat_100g, dtype: int64

=======================================================
Cholesterol_100g
0.0      11035
1.0        746
7.0        631
4.0        600
9.0        549
         ...
166.0        1
511.0        1
803.0        1
258.0        1
211.0        1
Name: Cholesterol_100g, Length: 263, dtype: int64

=======================================================
Sodium_100g
0.0       2071
2.0        617
3.0        609
4.0        582
1.0        547
          ...
1221.0       1
1642.0       1
1671.0       1
968.0        1
825.0        1
Name: Sodium_100g, Length: 1391, dtype: int64

=======================================================
Potassium_100g
0.0      88
2.0      16
60.0     11
66.0     11
222.0     9
         ..
42.0      1
250.0     1
203.0     1
320.0     1
119.0     1
Name: Potassium_100g, Length: 195, dtype: int64

=======================================================
Carbohydrates_100g
0.0       2653
12.0      1429
13.0      1314
11.0      1249
7.0       1136
          ...
613.0        1
107.0        1
1800.0       1
106.0        1
124.0        1
Name: Carbohydrates_100g, Length: 110, dtype: int64

=======================================================
Protein_100g
0.0      8784
1.0      3239
2.0      2384
3.0      1656
4.0      1322
9.0       835
11.0      763
5.0       740
10.0      699
12.0      661
7.0       599
8.0       580
6.0       520
13.0      514
14.0      366
15.0      279
16.0      226
17.0      213
18.0      152
20.0      149
19.0      139
21.0      135
22.0      105
25.0       72
29.0       66
24.0       62
23.0       49
26.0       41
28.0       35
27.0       29
33.0       26
34.0       12
30.0       10
35.0       10
32.0        8
31.0        8
40.0        5
36.0        4
45.0        4
38.0        3
42.0        3
43.0        3
48.0        2
41.0        2
49.0        2
100.0       2
55.0        1
425.0       1
92.0        1
37.0        1
99.0        1
133.0       1
141.0       1
60.0        1
157.0       1
44.0        1
71.0        1
39.0        1
63.0        1
Name: Protein_100g, dtype: int64

=======================================================
Sugar_100g
0.0      5258
2.0      2330
1.0      2001
3.0      1518
4.0      1242
         ...
158.0       1
72.0        1
370.0       1
350.0       1
109.0       1
Name: Sugar_100g, Length: 92, dtype: int64

=======================================================
Dietary_Fiber_100g
0.0      16441
1.0       5185
2.0       2291
3.0        651
4.0        390
5.0        141
7.0         79
6.0         76
8.0         25
11.0        25
10.0        24
9.0         17
12.0        16
14.0         7
17.0         5
19.0         2
15.0         2
25.0         2
13.0         2
39.0         2
18.0         1
26.0         1
32.0         1
63.0         1
100.0        1
49.0         1
400.0        1
21.0         1
Name: Dietary_Fiber_100g, dtype: int64

=======================================================
Calories_text
<5           17
0-5           6
770-1200      3
'10-25        3
3480-3720     3
             ..
0-280         1
630-930       1
480-900       1
720-1180      1
3480-3600     1
Name: Calories_text, Length: 238, dtype: int64

=======================================================
Total_Fat_text
68-70        3
'7-28        2
0-1          2
'1-5         2
4.3-15.4     2
'3-10        2
'1-4         2
65-68        2
71-74        2
51-63        1
'11-14       1
34-42        1
7.5-30       1
19-20        1
40-43        1
14-43        1
3.5-5        1
11.4-16.4    1
13-17.4      1
7.1-12       1
20.8-25.3    1
'5-7         1
23-24        1
41-82        1
'3-12        1
0-8          1
37-73        1
0-140        1
18-36        1
17-37        1
'7-29        1
43-77        1
119-131      1
52-55        1
17-41        1
73-76        1
23-33        1
85-88        1
68-100       1
'9-10        1
38-41        1
60-63        1
44-103       1
25-73        1
54-57        1
40-88        1
90-93        1
99-102       1
82-85        1
91-94        1
46-49        1
63-66        1
68-71        1
59-62        1
61-64        1
67-70        1
34-44        1
51-66        1
34-54        1
Name: Total_Fat_text, dtype: int64

=======================================================
Saturated_Fat_text
'1-3        3
0-1         2
1.8-7.9     2
23-24       2
18-19       2
21-22       2
'2-8        2
35-36       2
0-3         1
'6-18       1
'2-3        1
14-27       1
'1-4        1
8.5-10.2    1
4.9-6.1     1
18-27       1
13-26       1
3.7-5.9     1
7.1-8.8     1
6.2-7.9     1
'12-18      1
'1-2        1
'1-9        1
38-39       1
'1-1        1
22-23       1
'10-17      1
30-51       1
'8-9        1
'10-12      1
13-33       1
'6-23       1
'12-32      1
31-32       1
37-38       1
16-17       1
24-25       1
14-18       1
21-27       1
'9-19       1
'9-12.5     1
Name: Saturated_Fat_text, dtype: int64

=======================================================
Trans_Fat_text
'1-3     3
0-1      2
1.5-3    1
'7-15    1
'1-6     1
'1-2     1
'2-8     1
Name: Trans_Fat_text, dtype: int64

=======================================================
Cholesterol_text
<5           325
'10-15         2
<1             2
41.2-46.6      2
'1-4           2
'3-13          2
10.3-37.8      2
302-306        1
75-150         1
75-120         1
'1-2           1
35-95          1
30.1-33.6      1
22-33          1
36-44          1
160-175        1
120-190        1
43-63          1
45-110         1
60-105         1
40-70          1
605-688        1
303-370        1
523-1014       1
60-70          1
30-35          1
128-189        1
50-80          1
Name: Cholesterol_text, dtype: int64

=======================================================
Sodium_text
14-55        2
53-210       2
0-35         2
50-60        2
'3-10        2
            ..
1560-1620    1
4300-4360    1
3480-3540    1
4080-4140    1
1630-2430    1
Name: Sodium_text, Length: 82, dtype: int64

=======================================================
Potassium_text
450-470    1
<1         1
Name: Potassium_text, dtype: int64

=======================================================
Carbohydrates_text
<1         553
99-105       3
0-1          2
'10-40       2
105-111      2
          ...
36-58        1
66-67        1
'1-39        1
192-224      1
38-41        1
Name: Carbohydrates_text, Length: 75, dtype: int64

=======================================================
Protein_text
<1           406
43-45          2
59-60          2
29-31          2
'10-40         2
30.5-31.5      1
'5-21          1
39-41          1
0-1            1
0-2            1
'1-2           1
3.5-14         1
'1-5           1
96-98          1
39-50          1
'4-6           1
84-85          1
48-54          1
20.8-23.7      1
'3-13          1
'10-39         1
'12-13         1
'8-32          1
87-132         1
'10-41         1
25-50          1
58-88          1
'7-28          1
'5-19          1
30.6-31        1
71-72          1
32-36          1
27-33          1
'7-10          1
50-51          1
49-50          1
55-56          1
21-30          1
'2-4           1
'5-7           1
54-55          1
58-59          1
40-42          1
38-57          1
65-66          1
35-37          1
63-64          1
73-74          1
39-49          1
74-75          1
70-71          1
67-68          1
79-80          1
30-31          1
31-33          1
25-26          1
45-47          1
'3-24          1

Name: Protein_text, dtype: int64

=======================================================
Sugar_text
<1         536
'5-19        2
0-25         2
'5-18        2
'6-25        2
'7-26        2
'8-30        2
'6-26        2
'6-24        2
'7-27        2
'6-22        2
'9-11        2
'1-6         1
'5-17        1
'2-8         1
0-55         1
'1-2         1
0-1          1
18-21        1
'2-3         1
'6-42        1
19-38        1
'3-28        1
40-61        1
'4-28        1
'8-9         1
0-47         1
34-65        1
'1-30        1
'3-5         1
49-85        1
146-254      1
20-23        1
41-47        1
49-51        1
'5-6         1
'5-14        1
'8-11        1
'4-30        1
'6-45        1
0-30         1
'5-8         1
'7-10        1
0-41         1
'2-35        1
Name: Sugar_text, dtype: int64

=======================================================
Dietary_Fiber_text
<1        749
'8-9        9
-1          6
0-1         5
'7-8        4
'1-2        3
'5-6        3
'6-8        2
'2-4        2
'4-5        2
<1-1        2
'9-11       2
'10-12      2
'1-4        2
<1-4        1
'2-3        1
'2-5        1
'6-9        1
0-3         1
'4-6        1
0-5         1
19-20       1
'6-7        1
<8          1
'9-12       1
'7-9        1
'10-11      1
'11-12      1
'8-10       1
0-2         1
'2-12       1
0-30        1
Name: Dietary_Fiber_text, dtype: int64

=======================================================
Kids_Meal
0    61461
1     3758
Name: Kids_Meal, dtype: int64

=======================================================
Limited_Time_Offer
0    63103
1     2116
Name: Limited_Time_Offer, dtype: int64

=======================================================
Regional
0    63134
1     2085
Name: Regional, dtype: int64

=======================================================
Shareable
0    63351
1     1868
Name: Shareable, dtype: int64

=======================================================

### Checking for duplicate rows

In [16]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
65214    False
65215    False
65216    False
65217    False
65218    False
Length: 65219, dtype: bool

In [17]:
# Selecting duplicate based on all columns
duplicate = df[df.duplicated()]
  
print("Duplicate Rows :")
duplicate

Duplicate Rows :

Empty DataFrame
Columns: [Menu_Item_ID, Year, Restaurant_Item_Name, restaurant, Restaurant_ID, Item_Name, Item_Description, Food_Category, Serving_Size, Serving_Size_text, Serving_Size_Unit, Serving_Size_household, Calories, Total_Fat, Saturated_Fat, Trans_Fat, Cholesterol, Sodium, Potassium, Carbohydrates, Protein, Sugar, Dietary_Fiber, Calories_100g, Total_Fat_100g, Saturated_Fat_100g, Trans_Fat_100g, Cholesterol_100g, Sodium_100g, Potassium_100g, Carbohydrates_100g, Protein_100g, Sugar_100g, Dietary_Fiber_100g, Calories_text, Total_Fat_text, Saturated_Fat_text, Trans_Fat_text, Cholesterol_text, Sodium_text, Potassium_text, Carbohydrates_text, Protein_text, Sugar_text, Dietary_Fiber_text, Kids_Meal, Limited_Time_Offer, Regional, Shareable]
Index: []

[0 rows x 49 columns]

#### There are no duplicate entries in our dataset

---

## Data Profiling Summary 
### List of the issues that the data contains

1. In intial dataset, there were 65219 rows and 49 columns in our dataset.


2. These columns contain integer, float and categorical values.


3. We also observed unique values in each column.


4. The columns Calories_text, Total_Fat_text, Saturated_Fat_text, Trans_Fat_text, Cholesterol_text, Sodium_text,   Potassium_text,Carbohydrates_text,Protein_text,Sugar_text,Dietary_Fiber_text,Potassium,Potassium_100g,Serving_Size_text,Serving_Size,Serving_Size_Unit,Serving_Size_household do not proide relevant information for the model deployment. So these columns needs to be dropped. 


5. Since the major analysis will revolve around the calories column. The values that were na were dropped from the column.


6. There are missing vlaues in 19 columns.Since these are mostly related to nutrients, the na columns are filled with value zero for analysis.


---
---
---






# Data  Cleansing

### Dropping unwanted columns

In [28]:
# Dropping columns
df1=df.drop(['Calories_text', 'Total_Fat_text',
       'Saturated_Fat_text', 'Trans_Fat_text', 'Cholesterol_text',
       'Sodium_text', 'Potassium_text', 'Carbohydrates_text', 'Protein_text',
       'Sugar_text', 'Dietary_Fiber_text','Potassium','Potassium_100g','Serving_Size_text','Serving_Size','Serving_Size_Unit',
       'Serving_Size_household'],axis=1)

## Rename 'df1' columns
By making all the columns’ names in lowercase, and if the column name has a whitespace, replace it with an underscore. (For example: “Customer Type” will be renamed to “customer_type”).

In [29]:
df1.columns

Index(['Menu_Item_ID', 'Year', 'Restaurant_Item_Name', 'restaurant',
       'Restaurant_ID', 'Item_Name', 'Item_Description', 'Food_Category',
       'Calories', 'Total_Fat', 'Saturated_Fat', 'Trans_Fat', 'Cholesterol',
       'Sodium', 'Carbohydrates', 'Protein', 'Sugar', 'Dietary_Fiber',
       'Calories_100g', 'Total_Fat_100g', 'Saturated_Fat_100g',
       'Trans_Fat_100g', 'Cholesterol_100g', 'Sodium_100g',
       'Carbohydrates_100g', 'Protein_100g', 'Sugar_100g',
       'Dietary_Fiber_100g', 'Kids_Meal', 'Limited_Time_Offer', 'Regional',
       'Shareable'],
      dtype='object')

In [30]:
df1.rename(columns = lambda x: x.lower().replace(' ','_'), inplace= True)
df1.columns

Index(['menu_item_id', 'year', 'restaurant_item_name', 'restaurant',
       'restaurant_id', 'item_name', 'item_description', 'food_category',
       'calories', 'total_fat', 'saturated_fat', 'trans_fat', 'cholesterol',
       'sodium', 'carbohydrates', 'protein', 'sugar', 'dietary_fiber',
       'calories_100g', 'total_fat_100g', 'saturated_fat_100g',
       'trans_fat_100g', 'cholesterol_100g', 'sodium_100g',
       'carbohydrates_100g', 'protein_100g', 'sugar_100g',
       'dietary_fiber_100g', 'kids_meal', 'limited_time_offer', 'regional',
       'shareable'],
      dtype='object')

In [31]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65219 entries, 0 to 65218
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   menu_item_id          65219 non-null  int64
 1   year                  65219 non-null  int64
 2   restaurant_item_name  65219 non-null  object
 3   restaurant            65219 non-null  object
 4   restaurant_id         65219 non-null  int64
 5   item_name             65219 non-null  object
 6   item_description      65219 non-null  object
 7   food_category         65219 non-null  object
 8   calories              55315 non-null  float64
 9   total_fat             54846 non-null  float64
 10  saturated_fat         54143 non-null  float64
 11  trans_fat             51503 non-null  float64
 12  cholesterol           53219 non-null  float64
 13  sodium                54991 non-null  float64
 14  carbohydrates         54288 non-null  float64
 15  protein               54233 non-null  float64
 16  sugar                 52931 non-null  float64
 17  dietary_fiber         53440 non-null  float64
 18  calories_100g         25878 non-null  float64
 19  total_fat_100g        25686 non-null  float64
 20  saturated_fat_100g    25285 non-null  float64
 21  trans_fat_100g        23828 non-null  float64
 22  cholesterol_100g      25126 non-null  float64
 23  sodium_100g           25853 non-null  float64
 24  carbohydrates_100g    25592 non-null  float64
 25  protein_100g          25531 non-null  float64
 26  sugar_100g            25207 non-null  float64
 27  dietary_fiber_100g    25391 non-null  float64
 28  kids_meal             65219 non-null  int64
 29  limited_time_offer    65219 non-null  int64
 30  regional              65219 non-null  int64
 31  shareable             65219 non-null  int64
dtypes: float64(20), int64(7), object(5)
memory usage: 15.9+ MB


# Handle missing values
---
### There are a few options for handling missing values:

    - Remove any rows that have missing values.
    - Remove any columns that have missing values.
    - Fill the missing values with some other value.
    - Leave the missing values as is.

The first two options are often used to prepare data for machine learning algorithms, which are unable to be used with data that includes null values. We can use the **DataFrame.dropna()** method to remove or drop rows and columns with null values.

Syntax:

#### DataFrame.dropna(axis=0, how='any',  inplace=False)

Arguments:
###### axis: Default – 0
   -  0, or ‘index’ : Drop rows which contain NaN values.
   - 1, or ‘columns’ : Drop columns which contain NaN value.
    
###### how: Default – ‘any’
   - ‘any’ : Drop rows / columns which contain any NaN values.
   - ‘all’ : Drop rows / columns which contain all NaN values.
    
###### inplace (bool): Default- False
   - If True, modifies the calling dataframe object

In [32]:
# Number of missing values in each coulmn
df1.isnull().sum()

menu_item_id                0
year                        0
restaurant_item_name        0
restaurant                  0
restaurant_id               0
item_name                   0
item_description            0
food_category               0
calories                 9904
total_fat               10373
saturated_fat           11076
trans_fat               13716
cholesterol             12000
sodium                  10228
carbohydrates           10931
protein                 10986
sugar                   12288
dietary_fiber           11779
calories_100g           39341
total_fat_100g          39533
saturated_fat_100g      39934
trans_fat_100g          41391
cholesterol_100g        40093
sodium_100g             39366
carbohydrates_100g      39627
protein_100g            39688
sugar_100g              40012
dietary_fiber_100g      39828
kids_meal                   0
limited_time_offer          0
regional                    0
shareable                   0
dtype: int64

### Dropping the rows which has missing value in calorie column

In [34]:
df1.dropna(subset=['calories'], inplace=True)

In [35]:
df1.isnull().sum()

menu_item_id                0
year                        0
restaurant_item_name        0
restaurant                  0
restaurant_id               0
item_name                   0
item_description            0
food_category               0
calories                    0
total_fat                 550
saturated_fat            1254
trans_fat                3900
cholesterol              2185
sodium                    406
carbohydrates            1088
protein                  1169
sugar                    2443
dietary_fiber            1963
calories_100g           29437
total_fat_100g          29659
saturated_fat_100g      30060
trans_fat_100g          31529
cholesterol_100g        30226
sodium_100g             29502
carbohydrates_100g      29742
protein_100g            29816
sugar_100g              30127
dietary_fiber_100g      29960
kids_meal                   0
limited_time_offer          0
regional                    0
shareable                   0
dtype: int64

#### Fill the missing values with some other value. In this case it has been filled with zero.

In [36]:
df1 = df1.fillna(0)

In [37]:
df1.isnull().sum()

menu_item_id            0
year                    0
restaurant_item_name    0
restaurant              0
restaurant_id           0
item_name               0
item_description        0
food_category           0
calories                0
total_fat               0
saturated_fat           0
trans_fat               0
cholesterol             0
sodium                  0
carbohydrates           0
protein                 0
sugar                   0
dietary_fiber           0
calories_100g           0
total_fat_100g          0
saturated_fat_100g      0
trans_fat_100g          0
cholesterol_100g        0
sodium_100g             0
carbohydrates_100g      0
protein_100g            0
sugar_100g              0
dietary_fiber_100g      0
kids_meal               0
limited_time_offer      0
regional                0
shareable               0
dtype: int64

In [38]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55315 entries, 2 to 65218
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   menu_item_id          55315 non-null  int64
 1   year                  55315 non-null  int64
 2   restaurant_item_name  55315 non-null  object
 3   restaurant            55315 non-null  object
 4   restaurant_id         55315 non-null  int64
 5   item_name             55315 non-null  object
 6   item_description      55315 non-null  object
 7   food_category         55315 non-null  object
 8   calories              55315 non-null  float64
 9   total_fat             55315 non-null  float64
 10  saturated_fat         55315 non-null  float64
 11  trans_fat             55315 non-null  float64
 12  cholesterol           55315 non-null  float64
 13  sodium                55315 non-null  float64
 14  carbohydrates         55315 non-null  float64
 15  protein               55315 non-null  float64
 16  sugar                 55315 non-null  float64
 17  dietary_fiber         55315 non-null  float64
 18  calories_100g         55315 non-null  float64
 19  total_fat_100g        55315 non-null  float64
 20  saturated_fat_100g    55315 non-null  float64
 21  trans_fat_100g        55315 non-null  float64
 22  cholesterol_100g      55315 non-null  float64
 23  sodium_100g           55315 non-null  float64
 24  carbohydrates_100g    55315 non-null  float64
 25  protein_100g          55315 non-null  float64
 26  sugar_100g            55315 non-null  float64
 27  dietary_fiber_100g    55315 non-null  float64
 28  kids_meal             55315 non-null  int64
 29  limited_time_offer    55315 non-null  int64
 30  regional              55315 non-null  int64
 31  shareable             55315 non-null  int64
dtypes: float64(20), int64(7), object(5)
memory usage: 13.9+ MB

In [39]:
# Reset the index of the DataFrame
df1.reset_index(drop=True, inplace = True)
df1

,menu_item_id,year,restaurant_item_name,restaurant,restaurant_id,item_name,item_description,food_category,calories,total_fat,...,cholesterol_100g,sodium_100g,carbohydrates_100g,protein_100g,sugar_100g,dietary_fiber_100g,kids_meal,limited_time_offer,regional,shareable
0,35027,2017,7 Eleven French Vanilla Cappuccino,7 Eleven,1,French Vanilla Cappuccino,"French Vanilla Cappuccino, Coffee, Drinks, Fla...",Beverages,190.0,6.0,...,0.0,84.0,15.0,1.0,10.0,0.0,0,0,1,0
1,35028,2017,7 Eleven Peppermint Mocha,7 Eleven,1,Peppermint Mocha,"Peppermint Mocha, Coffee, 8 fl oz",Beverages,180.0,4.0,...,0.0,79.0,16.0,0.0,11.0,0.0,0,0,0,0
2,35029,2017,7 Eleven Pumpkin Spice Latte,7 Eleven,1,Pumpkin Spice Latte,"Pumpkin Spice Latte, Coffee, 8 fl oz",Beverages,190.0,6.0,...,0.0,84.0,15.0,0.0,12.0,0.0,0,0,1,0
3,35037,2017,7 Eleven Caramel Macchiato,7 Eleven,1,Caramel Macchiato,"Caramel Macchiato, also called Caramel Macchia...",Beverages,190.0,5.0,...,0.0,75.0,15.0,1.0,11.0,0.0,0,0,1,0
4,35042,2017,7 Eleven Hot Chocolate,7 Eleven,1,Hot Chocolate,"Hot Chocolate, Coffee, Drinks, Flavors Vary by...",Beverages,170.0,2.5,...,0.0,88.0,16.0,1.0,12.0,0.0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55310,118344,2018,"Einstein Bros Frozen Mocha, 24 fl oz",Einstein Bros,31,"Frozen Mocha, 24 fl oz","Frozen Mocha w/ 2% Milk, 24 fl oz, Classic, Be...",Beverages,680.0,16.0,...,7.0,25.0,19.0,1.0,17.0,0.0,0,0,0,0
55311,153014,2018,Dunkin' Donuts Sweet Black Pepper Bacon Wake U...,Dunkin' Donuts,30,Sweet Black Pepper Bacon Wake Up Wrap,"Sweet Black Pepper Bacon Wake Up Wrap, Breakfa...",Sandwiches,250.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
55312,174902,2018,LongHorn Steakhouse Whiskey Smash,LongHorn Steakhouse,53,Whiskey Smash,"Whiskey Smash w/ Jim Beam Bourbon, Fresh Squee...",Beverages,200.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
55313,131673,2018,Golden Corral Chicken Enchilada,Golden Corral,37,Chicken Enchilada,"Chicken Enchilada, Chicken & Turkey",Entrees,190.0,11.0,...,31.0,528.0,9.0,9.0,1.0,1.0,0,0,0,0
55314,136001,2018,"Del Taco Street Tacos, Carne Asada",Del Taco,27,"Street Tacos, Carne Asada",Street Tacos in 2 Tortillas w/ Carne Asada Ste...,Sandwiches,180.0,7.0,...,22.0,354.0,18.0,10.0,1.0,2.0,0,0,0,0

#### Unique values for each column after cleansing

In [40]:
# for each column
cols = df1.columns
for col in cols:
    print(col)

    # get a list of unique values
    unique = df1[col].unique()
    print(sorted(unique), '\n*************************************\n\n')

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [41]:
df1

,menu_item_id,year,restaurant_item_name,restaurant,restaurant_id,item_name,item_description,food_category,calories,total_fat,...,cholesterol_100g,sodium_100g,carbohydrates_100g,protein_100g,sugar_100g,dietary_fiber_100g,kids_meal,limited_time_offer,regional,shareable
0,35027,2017,7 Eleven French Vanilla Cappuccino,7 Eleven,1,French Vanilla Cappuccino,"French Vanilla Cappuccino, Coffee, Drinks, Fla...",Beverages,190.0,6.0,...,0.0,84.0,15.0,1.0,10.0,0.0,0,0,1,0
1,35028,2017,7 Eleven Peppermint Mocha,7 Eleven,1,Peppermint Mocha,"Peppermint Mocha, Coffee, 8 fl oz",Beverages,180.0,4.0,...,0.0,79.0,16.0,0.0,11.0,0.0,0,0,0,0
2,35029,2017,7 Eleven Pumpkin Spice Latte,7 Eleven,1,Pumpkin Spice Latte,"Pumpkin Spice Latte, Coffee, 8 fl oz",Beverages,190.0,6.0,...,0.0,84.0,15.0,0.0,12.0,0.0,0,0,1,0
3,35037,2017,7 Eleven Caramel Macchiato,7 Eleven,1,Caramel Macchiato,"Caramel Macchiato, also called Caramel Macchia...",Beverages,190.0,5.0,...,0.0,75.0,15.0,1.0,11.0,0.0,0,0,1,0
4,35042,2017,7 Eleven Hot Chocolate,7 Eleven,1,Hot Chocolate,"Hot Chocolate, Coffee, Drinks, Flavors Vary by...",Beverages,170.0,2.5,...,0.0,88.0,16.0,1.0,12.0,0.0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55310,118344,2018,"Einstein Bros Frozen Mocha, 24 fl oz",Einstein Bros,31,"Frozen Mocha, 24 fl oz","Frozen Mocha w/ 2% Milk, 24 fl oz, Classic, Be...",Beverages,680.0,16.0,...,7.0,25.0,19.0,1.0,17.0,0.0,0,0,0,0
55311,153014,2018,Dunkin' Donuts Sweet Black Pepper Bacon Wake U...,Dunkin' Donuts,30,Sweet Black Pepper Bacon Wake Up Wrap,"Sweet Black Pepper Bacon Wake Up Wrap, Breakfa...",Sandwiches,250.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
55312,174902,2018,LongHorn Steakhouse Whiskey Smash,LongHorn Steakhouse,53,Whiskey Smash,"Whiskey Smash w/ Jim Beam Bourbon, Fresh Squee...",Beverages,200.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
55313,131673,2018,Golden Corral Chicken Enchilada,Golden Corral,37,Chicken Enchilada,"Chicken Enchilada, Chicken & Turkey",Entrees,190.0,11.0,...,31.0,528.0,9.0,9.0,1.0,1.0,0,0,0,0
55314,136001,2018,"Del Taco Street Tacos, Carne Asada",Del Taco,27,"Street Tacos, Carne Asada",Street Tacos in 2 Tortillas w/ Carne Asada Ste...,Sandwiches,180.0,7.0,...,22.0,354.0,18.0,10.0,1.0,2.0,0,0,0,0

# Export the cleaned dataset to CSV file.

In [43]:
#Exporting data into csv file
df1.to_csv("NYC_Menu.csv", index= False)